### ISSUE TITLE
Question: SyntaxError: Unexpected token `{` when run yarn in the desktop folder

### ISSUE THREAD

**Issue by maxim-pandra** [facebook/flipper#1109]
I am trying to build desktop application on Ubuntu 18.04. When I run yarn in desktop folder I'm getting following output with strange Syntax Error. What could I do to resolve it?
```
maksim@maksim-GT72VR-6RE:~/IdeaProjects/flipper/desktop$ yarn
yarn install v1.22.4
$ node scripts/prepare-watchman-config.js && yarn config set ignore-engines
yarn config v1.22.4
success Set "ignore-engines" to true.
Done in 0.04s.
[1/4] Resolving packages...
warning Resolution field "minimist@1.2.3" is incompatible with requested version "minimist@0.0.8"
warning Resolution field "minimist@1.2.3" is incompatible with requested version "minimist@^1.2.5"
warning Resolution field "acorn@7.1.1" is incompatible with requested version "acorn@^5.5.3"
warning Resolution field "ws@7.2.3" is incompatible with requested version "ws@^5.2.0"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^3.0.2"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^3.2.0"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^5.0.0"
warning Resolution field "acorn@7.1.1" is incompatible with requested version "acorn@^6.0.1"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^3.0.2"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^3.0.2"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^3.0.2"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^4.0.0"
warning Resolution field "kind-of@6.0.3" is incompatible with requested version "kind-of@^3.0.3"
warning Resolution field "temp@0.9.0" is incompatible with requested version "temp@0.8.3"
warning Resolution field "minimist@1.2.3" is incompatible with requested version "minimist@^1.2.5"
warning Resolution field "minimist@1.2.3" is incompatible with requested version "minimist@^1.2.5"
warning Resolution field "ws@7.2.3" is incompatible with requested version "ws@~6.1.0"
warning Resolution field "adbkit-logcat@2.0.1" is incompatible with requested version "adbkit-logcat@^1.1.0"
warning Resolution field "ws@7.2.3" is incompatible with requested version "ws@7.1.0"
warning Resolution field "minimist@1.2.3" is incompatible with requested version "minimist@^1.2.5"
warning Resolution field "minimist@1.2.3" is incompatible with requested version "minimist@~0.0.1"
warning Resolution field "minimist@1.2.3" is incompatible with requested version "minimist@0.0.8"
success Already up-to-date.
$ patch-package && ./ts-node scripts/yarn-install-fb-plugins.ts && yarn build:pkg && ./ts-node scripts/generate-plugin-entry-points.ts
patch-package 6.2.2
Applying patches...
adbkit@2.11.1 ✔
adbkit-logcat@2.0.1 ✔
jsonparse@1.3.1 ✔
metro@0.59.0 ✔
/home/maksim/IdeaProjects/flipper/desktop/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/maksim/IdeaProjects/flipper/desktop/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by passy** [comment]
Hey @maxim-pandra, that looks like you're running on a very old version of Node. Could you make sure you're on at least Node 10?

**Comment by mweststrate** [comment]
Closing for inactivity & solved
