### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread

### ISSUE THREAD

**Issue by soroushm** [facebook/flipper#1207]
## 🐛 Bug Report
I clean Gradle and node_modules and install it again it happened
same situation on production build
are that possible Gradle packages is incompatible?
```
--------- beginning of crash
2020-05-30 19:56:01.902 31379-31513/? E/AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread
    Process: com.xxxx.debug, PID: 31379
    java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
2020-05-30 19:56:01.902 31379-31512/? E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.xxxx.debug, PID: 31379
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:25)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:44)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

## Environment
"react": "16.11.0",
"react-native": "0.62.2",

**Comment by soroushm** [comment]
Dublicate issue
#28163
I try `rm -rf $HOME/.gradle/caches/` few times but didn't work only command below work for me

cd android/
Run
./gradlew clean

That should probably fix this.
