### ISSUE TITLE
Question: Which Android API level is the minimum supported?

### ISSUE THREAD

**Issue by Zloka** [facebook/flipper#1225]
When building my (React Native) Android app, I get the following stacktrace on lower API levels. The only reference I can find to something about the OkHttpClient is related to Flipper, which lead me here. My React Native project is pretty vanilla still (with `multiDex` enabled), so I figured this might be a relatively common occurence?
```
06-05 13:59:06.823 1274-1274/fi.mafynetti.mafyclient E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fi.mafynetti.mafyclient, PID: 1274
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fi.mafynetti.mafyclient/fi.mafynetti.mafyclient.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
        at android.app.ActivityThread.access$900(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:90)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
        at fi.mafynetti.mafyclient.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:5451)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
        at android.app.ActivityThread.access$900(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at fi.mafynetti.mafyclient.MainActivity.onCreate(MainActivity.java:22) 
        at android.app.Activity.performCreate(Activity.java:5451) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
        at android.app.ActivityThread.access$900(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132)
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at fi.mafynetti.mafyclient.MainActivity.onCreate(MainActivity.java:22) 
        at android.app.Activity.performCreate(Activity.java:5451) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
        at android.app.ActivityThread.access$900(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132) 
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104) 
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90) 
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85) 
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45) 
        at fi.mafynetti.mafyclient.MainActivity.onCreate(MainActivity.java:22) 
        at android.app.Activity.performCreate(Activity.java:5451) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
        at android.app.ActivityThread.access$900(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by mweststrate** [comment]
cc @passy

**Comment by passy** [comment]
@Zloka The error doesn't have any Flipper-related parts in the stacktrace, but arises from React Native. Could you please ask there?

**Comment by sunnylqm** [comment]
@passy  But disabling flipper works for android 4.x devices 
https://github.com/facebook/react-native/issues/28481
