### ISSUE TITLE
database: error default value of column is not constant

### ISSUE THREAD

**Issue by likern** [facebook/flipper#1499]
## 🐛 Bug Report
I've created sqlite database table (using TypeORM) with the following SQL statement
```sql
CREATE TABLE "tasks" ("id" text PRIMARY KEY NOT NULL, "author" text NOT NULL, "title" text NOT NULL, "createdAt" datetime NOT NULL, "completedAt" datetime, "isArchived" boolean NOT NULL DEFAULT (false), "isCompleted" boolean NOT NULL DEFAULT (false), "isTracked" boolean NOT NULL, "trackedSeconds" real)
```

where column `isArchived` setup with **FALSE** as **DEFAULT VALUE**
```sql
"isArchived" boolean NOT NULL DEFAULT (false)
```

**FALSE** is a valid literal and I don't see error in table creation.

I could successfully test that ommiting **isArchived** column works
```sql
INSERT INTO "tasks"("id", "author", "title", "createdAt", "completedAt", "isCompleted", "isTracked", "trackedSeconds") 
VALUES ('testbd317a-3a1b-43cb-8e93-c768032168a1', 'Q3mwjQWQxTRm06L11YeALBaW2Fg2', 'Test', '2020-08-24 18:04:36.798', '', '0', '0', '')
```

and **DEFAULT VALUE** _false_ (means 0) is used.

**But**, if I try to open this database using Flipper I see **error** in log.
```
Time	Tag	App	Message
22:27:11.070	SQLiteLog		(1) default value of column [isArchived] is not constant
22:27:11.070	SQLiteLog		(11) database corruption at line 117836 of [68b898381a]
22:27:11.070	SQLiteLog		(11) malformed database schema (tasks) - default value of column [isArchived] is not constant
```

```
Time	      Tag	                 App	Message
22:27:11.071 SQLiteDatabase Database corruption detected in open()
android.database.sqlite.SQLiteDatabaseCorruptException: malformed database schema (tasks) - default value of column [isArchived] is not constant (code 11 SQLITE_CORRUPT): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:729)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:376)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:316)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:786)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:733)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver$2.openDatabase(SqliteDatabaseDriver.java:64)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:94)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:31)
	at com.facebook.flipper.plugins.databases.ObjectMapper.databaseListToFlipperArray(ObjectMapper.java:41)
	at com.facebook.flipper.plugins.databases.DatabasesManager$2.onReceive(DatabasesManager.java:85)
	at com.facebook.flipper.android.EventBase.loopForever(Native Method)
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:31)

```

This finally results in deleting "corrupted" database
```
	Time	Tag	App	Message
	22:27:11.071	DefaultDatabaseErrorHandler		Corruption reported by sqlite on database: /data/user/0/com.breeffy.feeve/databases/smarty.db
	22:27:11.142	SQLiteDatabase		DB wipe detected: package=com.breeffy.feeve reason=corruption file=/data/user/0/com.breeffy.feeve/databases/smarty.db ctime=2020-08-24T19:26:50Z mtime=2020-08-24T19:26:50Z atime=2020-08-24T19:26:36Z checkfile [unable to obtain timestamp]
java.lang.Throwable: STACKTRACE
	at android.database.sqlite.SQLiteDatabase.wipeDetected(SQLiteDatabase.java:2741)
	at android.database.DefaultDatabaseErrorHandler.onCorruption(DefaultDatabaseErrorHandler.java:55)
	at android.database.sqlite.SQLiteDatabase.onCorruption(SQLiteDatabase.java:399)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:786)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:733)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver$2.openDatabase(SqliteDatabaseDriver.java:64)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:94)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:31)
	at com.facebook.flipper.plugins.databases.ObjectMapper.databaseListToFlipperArray(ObjectMapper.java:41)
	at com.facebook.flipper.plugins.databases.DatabasesManager$2.onReceive(DatabasesManager.java:85)
	at com.facebook.flipper.android.EventBase.loopForever(Native Method)
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:31)

	22:27:11.143	SQLiteDatabase		DB wipe detected: package=com.breeffy.feeve reason=corruption file=/data/user/0/com.breeffy.feeve/databases/smarty.db ctime=2020-08-24T19:26:50Z mtime=2020-08-24T19:26:50Z atime=2020-08-24T19:26:36Z checkfile [unable to obtain timestamp]
	22:27:11.143	SQLiteDatabase		at java.lang.Throwable: STACKTRACE
	at android.database.sqlite.SQLiteDatabase.wipeDetected(SQLiteDatabase.java:2741)
	at android.database.DefaultDatabaseErrorHandler.onCorruption(DefaultDatabaseErrorHandler.java:55)
	at android.database.sqlite.SQLiteDatabase.onCorruption(SQLiteDatabase.java:399)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:786)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:733)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver$2.openDatabase(SqliteDatabaseDriver.java:64)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:94)
	at com.facebook.flipper.plugins.databases.impl.SqliteDatabaseDriver.getTableNames(SqliteDatabaseDriver.java:31)
	at com.facebook.flipper.plugins.databases.ObjectMapper.databaseListToFlipperArray(ObjectMapper.java:41)
	at com.facebook.flipper.plugins.databases.DatabasesManager$2.onReceive(DatabasesManager.java:85)
	at com.facebook.flipper.android.EventBase.loopForever(Native Method)
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:31)

	22:27:11.143	SQLiteDatabase		DB wipe detected: package=com.breeffy.feeve reason=corruption file=/data/user/0/com.breeffy.feeve/databases/smarty.db ctime=2020-08-24T19:26:50Z mtime=2020-08-24T19:26:50Z atime=2020-08-24T19:26:36Z checkfile [unable to obtain timestamp]
```

**This table is valid and not corrupted, it should not lead to error and database deletion.**

## To Reproduce
1. Create table with false as default value.
2. Try to open database in Flipper

**Comment by mweststrate** [comment]
@likern afaik we pass all queries quite verbatim to the application. Of course we might not manage the connection to sqlite/ mobbly correctly, but, as maintainer of mobbly you are probably in a much better position to determine if we set up things correctly than we are :). You can take a look at how things are communicated with the database here: https://github.com/facebook/flipper/blob/54ebb44ddab24a0b157701d7c69af469fd5c4769/android/src/main/java/com/facebook/flipper/plugins/databases/DatabasesManager.java

**Comment by likern** [comment]
@mweststrate Thanks to give better understanding. I think it's an **sqlite-android** is [responsible for handling this](https://github.com/requery/sqlite-android/blob/0f1f31e9eecabe5fb33a35dba6c99db6c5758346/sqlite-android/src/main/jni/sqlite/android_database_SQLiteConnection.cpp#L377).

For those, who just wants to get quick fix (in TypeORM):

**For TypeORM migration**
```ts
    await queryRunner.createTable(
      new Table({
        name: 'tasks',
        columns: [
          {
            name: 'isArchived',
            type: 'boolean',
            default: Number(false)
          },
          {
            name: 'isCompleted',
            type: 'boolean',
            default: Number(false)
          }
        ]
      }),
      true
    );
```
**Or Entity description**
```ts
@Entity({ name: 'tasks' })
export class Task {
  @Column({ type: 'boolean', default: Number(false) })
  isArchived: boolean;

  @Column({ type: 'boolean', default: Number(false) })
  isCompleted: boolean;
}
```

Use **Number(false)** instead of **false**.
