### ISSUE TITLE
createTablePlugin not working

### ISSUE THREAD

**Issue by Dkhusainov** [facebook/flipper#1580]
## 🐛 Bug Report
Table plugin from https://fbflipper.com/docs/extending/create-table-plugin/ not working

## To Reproduce
1. Copypaste table plugin from docs above and pack plugin
2. Load plugin in Flipper
3. See error in Flipper console `Flipper plugin 'test' should export named function called 'plugin'

## Environment
Flipper: 0.61.0

**Comment by Dkhusainov** [comment]
Exporting the function leads to `Cannot read property 'supportsDevice' of undefined`

**Comment by mweststrate** [comment]
@Dkhusainov what does your `package.json` look like? Note that it should _not_ depend on `flipper-plugin`, as then we will load it as a new plugin format which is currently under development

**Comment by Dkhusainov** [comment]
The problem was indeed because of `flipper-plugin` dependency, don't remember how it got there. Thanks!

**Comment by afaucogney** [comment]
I'm in the same situation. Did you remember what's happened ?

Here is the error I get.

```
Plugin OkHttpCachePlugin failed to load Error: Flipper plugin 'OkHttpCachePlugin' should export named function called 'plugin'
    at new SandyPluginDefinition (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:1389:657)

    at requirePluginInternal (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:4577:3985)

    at file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:4577:3785

    at tryCatchReportPluginFailures (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:3447:1105)

    at requirePlugin (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:4577:3780)

    at file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:4577:3530

    at Array.map (<anonymous>)

    at e.default (file:///Applications/Flipper.app/Contents/Resources/app/bundle.js:4577:2566)`
```

The Package.json file:
```
{
  "$schema": "https://fbflipper.com/schemas/plugin-package/v2.json",
  "name": "flipper-plugin-okhttpcacheplugin",
  "id": "OkHttpCachePlugin",
  "version": "1.0.0",
  "main": "dist/bundle.js",
  "flipperBundlerEntry": "src/index.tsx",
  "license": "MIT",
  "keywords": [
    "flipper-plugin"
  ],
  "icon": "apps",
  "title": "OkHttp Cache Plugin",
  "scripts": {
    "lint": "flipper-pkg lint",
    "prepack": "flipper-pkg lint && flipper-pkg bundle",
    "build": "flipper-pkg bundle",
    "watch": "flipper-pkg bundle --watch",
    "test": "jest"
  },
  "peerDependencies": {
    "antd": "latest",
    "flipper": "0.66.0",
    "flipper-plugin": "0.66.0"
  },
  "devDependencies": {
    "@babel/preset-react": "latest",
    "@babel/preset-typescript": "latest",
    "@types/jest": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "antd": "latest",
    "flipper": "0.66.0",
    "flipper-pkg": "0.66.0",
    "flipper-plugin": "0.66.0",
    "jest": "latest"
  }
}
```
PS : This is my first play with flipper, so it may be something trivial !

**Comment by mweststrate** [comment]
Remove flipper-plugin from the deps, as that will opt you in into the new
plugin format.
