### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid URL port: "0"

### ISSUE THREAD

**Issue by boerdjamin** [facebook/flipper#1597]
```
FATAL EXCEPTION: AsyncTask #1001 
E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
```
[...]
```
E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid URL port: "0"
E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:916)
E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:165)
E AndroidRuntime: 	at com.facebook.react.packagerconnection.ReconnectingWebSocket.connect(ReconnectingWebSocket.java:71)
E AndroidRuntime: 	at com.facebook.react.packagerconnection.JSPackagerClient.init(JSPackagerClient.java:87)
E AndroidRuntime: 	at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:194)
E AndroidRuntime: 	at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:141)
E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:334)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

```

Got this error after adding a native module (using 'androidx.biometric:biometric:1.0.1' package). App builds, but immediately crashes on start

* Crashes on emulator (Nexus 5, API Level 29, Android 10)
* Crashed on device (HUAWEI P30 lite, Android 9)
* Flipper version 0.54.0
* Gradle version 4.0.1

**Comment by nikoant** [comment]
Hi @boerdjamin, could you make and share a repo where we can reproduce this?
