### ISSUE TITLE
Yarn install fails async function prepareWatchmanConfig

### ISSUE THREAD

**Issue by jbfitb** [facebook/flipper#1654]
## 🐛 Bug Report
`yarn install` fails with:

```
yarn install v1.22.4
$ node scripts/prepare-watchman-config.js && yarn config set ignore-engines
/Users/me/flipper/desktop/scripts/prepare-watchman-config.js:19
async function prepareWatchmanConfig(dir) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## To Reproduce
1. Check out the latest master
2. Ensure yarn is the latest version
3. cd `desktop`
4. Run `yarn install`

Expected:
Install works

Actual:
Install fails with the above error

## Environment
macOS 10.15.7
yarn version: 1.22.4

**Comment by mweststrate** [comment]
You probably need a newer node version
