### ISSUE TITLE
Error in logcat in Android about InspectorFlipperPlugin

### ISSUE THREAD

**Issue by afaucogney** [facebook/flipper#1736]
## 🐛 Bug Report

Error log in Logcat

```
D/ContextDescriptor: Failed to generate theme attribute data!
    java.lang.NoSuchFieldException: No field mKey in class Landroid/content/res/ResourcesImpl$ThemeImpl; (declaration of 'android.content.res.ResourcesImpl$ThemeImpl' appears in /system/framework/framework.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.ContextDescriptorUtils.collectThemeValues(ContextDescriptorUtils.java:58)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.ContextDescriptorUtils.themeData(ContextDescriptorUtils.java:34)
        at com.facebook.flipper.plugins.inspector.descriptors.ApplicationDescriptor.getData(ApplicationDescriptor.java:210)
        at com.facebook.flipper.plugins.inspector.descriptors.ApplicationDescriptor.getData(ApplicationDescriptor.java:29)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin$15.runOrThrow(InspectorFlipperPlugin.java:581)
        at com.facebook.flipper.core.ErrorReportingRunnable.run(ErrorReportingRunnable.java:24)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin.getNode(InspectorFlipperPlugin.java:585)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin.access$200(InspectorFlipperPlugin.java:31)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin$2.onReceiveOnMainThread(InspectorFlipperPlugin.java:179)
        at com.facebook.flipper.plugins.common.MainThreadFlipperReceiver$1.run(MainThreadFlipperReceiver.java:29)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## To Reproduce

```
    private fun setupFlipper() {
        SoLoader.init(this, false)
        if (FlipperUtils.shouldEnableFlipper(this)) {
            val client: FlipperClient = AndroidFlipperClient.getInstance(this)
            with(client) {
                addPlugin(InspectorFlipperPlugin(this@DebugEDFApplication, DescriptorMapping.withDefaults()))
                addPlugin(KTP.openRootScope().getInstance(NetworkFlipperPlugin::class.java))
                addPlugin(KTP.openRootScope().getInstance(DatabasesFlipperPlugin::class.java))
                addPlugin(KTP.openRootScope().getInstance(SharedPreferencesFlipperPlugin::class.java))
                addPlugin(CrashReporterPlugin.getInstance())
                start()
            }
        }
    }
```

## Environment

- Emulator on Android 10
- Flipper with version 0.66 or 0.67

**Comment by passy** [comment]
Thanks for the report. Does the rest of the plugin work as expected? I assume the theme information will be missing.

**Comment by afaucogney** [comment]
I'm new to flipper, and I'm not yet at the level to see if it doest work perfectly. I can see the layout structure + get detail info in the right bar. That's all !

**Comment by pikzen** [comment]
Bringing this back from the dead, because I still have the problem. Flipper 0.114.

```
java.lang.NoSuchFieldException: No field mKey in class Landroid/content/res/ResourcesImpl$ThemeImpl; (declaration of 'android.content.res.ResourcesImpl$ThemeImpl' appears in /system/framework/framework.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.ContextDescriptorUtils.collectThemeValues(ContextDescriptorUtils.java:58)
        at com.facebook.flipper.plugins.inspector.descriptors.utils.ContextDescriptorUtils.themeData(ContextDescriptorUtils.java:34)
        at com.facebook.flipper.plugins.inspector.descriptors.ViewDescriptor.getData(ViewDescriptor.java:193)
        at com.company.flipper.AdditionalViewDescriptor.getData(AdditionalViewDescriptor.kt:10)
        at com.company.flipper.AdditionalViewDescriptor.getData(AdditionalViewDescriptor.kt:8)
        at com.facebook.flipper.plugins.inspector.descriptors.TextViewDescriptor.getData(TextViewDescriptor.java:85)
        at com.facebook.flipper.plugins.inspector.descriptors.TextViewDescriptor.getData(TextViewDescriptor.java:27)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin$15.runOrThrow(InspectorFlipperPlugin.java:579)
        at com.facebook.flipper.core.ErrorReportingRunnable.run(ErrorReportingRunnable.java:24)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin.getNode(InspectorFlipperPlugin.java:583)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin.access$200(InspectorFlipperPlugin.java:31)
        at com.facebook.flipper.plugins.inspector.InspectorFlipperPlugin$5.onReceiveOnMainThread(InspectorFlipperPlugin.java:227)
        at com.facebook.flipper.plugins.common.MainThreadFlipperReceiver$1.run(MainThreadFlipperReceiver.java:29)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:245)
        at android.app.ActivityThread.main(ActivityThread.java:8004)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

Although I am currently using an additional layer on top of the regular ViewDescriptor to get some dp values and others, this issue also appears with the regular ViewDescriptor. Device is a OnePlus, with Android 11. As far as I can see, `mThemeImpl` does have an `mKey` field:

`private final Resources.ThemeKey mKey = new Resources.ThemeKey();`

As far as I know, Android 11+ introduced a set of hardening methods that prevent some reflection calls from being made. According to [this link](https://developer.android.com/guide/app-compatibility/restrictions-non-sdk-interfaces), mKey is indeed part of the restricted APIs, being part of `greylist-max-o` at line 52867.

It seems like some people have found ways to bypass it, but that might be a little bit too aggressive: https://github.com/ChickenHook/RestrictionBypass. Additionally, if some people have Flipper in their releases build pushed to production (why you would is another question), that'd be a sure way to be rejected.
