### ISSUE TITLE
Running sonar on windows 

### ISSUE THREAD

**Issue by anasanasanas** [facebook/flipper#176]
Yarn version 1.5.1

` TypeError: babelTemplate is not a function
    at Object.<anonymous> (C:\Users\user\Documents\Sonar\static\node_modules\metro\src\ModuleGraph\worker\collectDependencies.js:132:39)
    at Object.<anonymous> (C:\Users\user\Documents\Sonar\static\node_modules\metro\src\ModuleGraph\worker\collectDependencies.js:214:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\Documents\Sonar\static\node_modules\metro\src\JSTransformer\worker\index.js:16:29)`

**Comment by passy** [comment]
Cleaning up old issues and pull requests. Please let us know if this is something that's still relevant and we can reopen this and take another look. Thanks!
