### ISSUE TITLE
yarn build on mac fail

### ISSUE THREAD

**Issue by Whoisurdady** [facebook/flipper#194]
I' m fine with yarn start.
when i 
yarn build  --mac, it build successfully, but the built app run and shows a blank window
i am very confused

**Comment by passy** [comment]
Can you please provide any error information you get from either the console or the dev tools?

**Comment by Whoisurdady** [comment]
Here is my build log，I am working on MacOs High Sierra 10.13.6

yarn run v1.9.2
$ yarn rm-dist && NODE_ENV=production node scripts/build-release.js $@ --mac --version
$ rm -rf dist
Creating build directory
Created build directory /var/folders/zw/9dmk03k51rjbyh25p4s2ds6h0000gn/T/tmp-770oEZGfbvXsA4C
🕵️‍  Watching for plugin changes
⚙️  Compiling sonar-plugin-layout...
⚙️  Compiling sonar-plugin-network...
⚙️  Compiling sonar-plugin-sandbox...
⚙️  Compiling sonar-plugin-sharedpreferences...
Looking for JS files in
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac/src/plugins/layout
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac 

Looking for JS files in
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac/src/plugins/network
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac 

Looking for JS files in
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac/src/plugins/sandbox
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac 

Looking for JS files in
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac/src/plugins/shared_preferences
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac 

Loading dependency graph, done.
Loading dependency graph, done.
Loading dependency graph, done.
Loading dependency graph, done.
Writing bundle output to: /var/folders/zw/9dmk03k51rjbyh25p4s2ds6h0000gn/T/tmp-770oEZGfbvXsA4C/defaultPlugins/sonar-plugin-sandbox@1.0.0.js
Done writing bundle output
Writing bundle output to: /var/folders/zw/9dmk03k51rjbyh25p4s2ds6h0000gn/T/tmp-770oEZGfbvXsA4C/defaultPlugins/sonar-plugin-layout@1.0.0.js
Done writing bundle output
Writing bundle output to: /var/folders/zw/9dmk03k51rjbyh25p4s2ds6h0000gn/T/tmp-770oEZGfbvXsA4C/defaultPlugins/sonar-plugin-sharedpreferences@1.0.0.js
Done writing bundle output
Writing bundle output to: /var/folders/zw/9dmk03k51rjbyh25p4s2ds6h0000gn/T/tmp-770oEZGfbvXsA4C/defaultPlugins/sonar-plugin-network@1.0.0.js
Done writing bundle output
✅  Compiled all plugins.
Building main bundle /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac/src/init.js
Looking for JS files in
   /Users/zhaojian/MomoProjects/molive/android_hanisdk/momosonar/sonar_mac 

Loading dependency graph, done.
warning: the transform cache was reset.
Writing bundle output to: /var/folders/zw/9dmk03k51rjbyh25p4s2ds6h0000gn/T/tmp-770oEZGfbvXsA4C/bundle.js
Done writing bundle output
Creating package.json manifest
  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • skipped app dependencies rebuild reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=2.0.5 appOutDir=dist/mac
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                  0 identities found
                                             
                                               Valid identities only
                                                  0 valid identities found
  • building        target=macOS zip arch=x64 file=dist/Sonar-mac.zip
✨  Done
✨  Done in 127.47s.

**Comment by danielbuechele** [comment]
Can you try launching the app you build via the terminal like this: `/Applications/Sonar.app/Contents/MacOS/Sonar`. This should give you some more detailed error logs.

**Comment by Whoisurdady** [comment]
Here is my log

➜  MacOS git:(master) ✗ ./Sonar 
🕵️‍  Watching for plugin changes
✅  Compiled all plugins.
2018-08-07 18:41:47.069 Sonar[40703:2457913] *** WARNING: Textured window <AtomNSWindow: 0x7fad8f777e80> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by Whoisurdady** [comment]
Will someone help to solve this problem? or at least tell me why? Or change a dev-environment works?

**Comment by danielbuechele** [comment]
Are you able to open Chrome dev-tools inside of Sonar? Are there any errors on the console?
I see that you don't have a valid code-signing cert installed. This might also be an issue.

**Comment by Whoisurdady** [comment]
bundle.js:8541 Error: Could not call remote function 'setFeedURL'. Check that the function signature is correct. Underlying error: Could not get code signature for running application
Error: Could not call remote function 'setFeedURL'. Check that the function signature is correct. Underlying error: Could not get code signature for running application
    at callFunction (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (/Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/electron.asar/renderer/api/remote.js:125:16)
    at AutoUpdateVersion.componentDidMount (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:83791:38)
    at bi (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9462:114)
    at Wh (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9231:217)
    at Zh (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9190:173)
    at Xh (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9184:5)
    at Bh (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9143:62)
    at pg (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9071:34)
    at hi (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9662:5)
    at ji (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9677:12)
    at ri.render (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9846:5)
    at file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9924:70
    at di (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9588:12)
    at ui (file:///Users/zhoukai/Desktop/momo_flipper_mac/sonar_mac/dist/mac/Sonar.app/Contents/Resources/app.asar/bundle.js:9923:7)

**Comment by danielbuechele** [comment]
Ok, this is the line that is crashing: https://github.com/facebook/flipper/blob/75dfbf51f85ea466af0cf5ffdcac8326fe74722d/src/chrome/AutoUpdateVersion.js#L41
You could either install a valid cert to code sign your app, or we wrap this call in a try-catch-block.

**Comment by Whoisurdady** [comment]
How to install a valid cert? I am not a mac app developer, will u give some suggest?

**Comment by danielbuechele** [comment]
Open Xcode, go to preferences, Accounts, make sure your Apple ID is added here, click on manage certificates, click on the plus in the lower left corner, select "Mac Development". After that, a certificate should be generated that is then used automatically to sign your electron builds.

If that doesn't work, probably it's not worth wasting too much time on code signing and you should simply catch the error that is thrown.

**Comment by Whoisurdady** [comment]
Thanks a lot!
