### ISSUE TITLE
Fliper v0.77.0 can not start on MacOS Big Sur

### ISSUE THREAD

**Issue by vladamx** [facebook/flipper#1964]
## 🐛 Bug Report
TypeError: Cannot read property 'has' of undefined

Component stack:

    at ConnectFunction (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:36:976)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1836)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:67:145)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at ContextMenuProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:62:1195)
    at PopoverProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4718:132)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3018:3008)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:29:917)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3:941)

Error stacktrace:
TypeError: Cannot read property 'has' of undefined
    at isPluginEnabled (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:404)
    at Function.M.setPluginState [as mapToProps] (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4132:8548)
    at mapToPropsProxy (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:45:529)
    at Function.detectFactoryAndVerify (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:45:689)
    at mapToPropsProxy (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:45:511)
    at handleFirstCall (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:51:1425)
    at pureFinalPropsSelector (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:51:1463)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:36:1960
    at Object.useMemo (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:64997)
    at e.useMemo (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:7:5780)
    at ConnectFunction (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:36:1904)
    at Ch (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:59074)
    at li (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:68595)
    at ki (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67929)
    at ii (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67587)
    at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:114730)

**Comment by mweststrate** [comment]
@nikoant looks like the `enabledDevicePlugins` set is `undefined` from the stacktrace: https://github.com/facebook/flipper/blob/master/desktop/app/src/reducers/connections.tsx#L647. Any idea what might cause that?

**Comment by nikoant** [comment]
> @nikoant looks like the `enabledDevicePlugins` set is `undefined` from the stacktrace: https://github.com/facebook/flipper/blob/master/desktop/app/src/reducers/connections.tsx#L647. Any idea what might cause that?

This field is persisted to local storage, and it was renamed recently with a migration. Probably something wrong with it. I'll take care of this.

**Comment by mweststrate** [comment]
@vladamx as work around: if you can reach the settings screen there is a button to forget local data. Otherwise you can probably achieve the same through view > Toggle Developer Tools > Application tab > Clear storage.

**Comment by vladamx** [comment]
@mweststrate Managed to launch the app after PC restart. The bug was caused directly after the upgrade. The upgrade itself was just replacing the .dmg file.

**Comment by nikoant** [comment]
> @mweststrate Managed to launch the app after PC restart. The bug was caused directly after the upgrade. The upgrade itself was just replacing the .dmg file.

Have you updated from 0.76 or from an earlier version?

**Comment by vladamx** [comment]
@nikoant Earlier

**Comment by Jackmekiss** [comment]
Same error here

**Comment by mweststrate** [comment]
Should be fixed in Flipper 0.78
