### ISSUE TITLE
Crash error detected in desktop app [0.78.0] version of flipper

### ISSUE THREAD

**Issue by jayshah123** [facebook/flipper#1989]
## 🐛 Bug Report

Crash error detected in desktop app [0.78.0] version of flipper## To Reproduce

flipper and emulator were left idle for a while.
Device logs menu  itemwas selected.
Then I started developing again which caused a fast refresh.
I checked flipper and saw this error.
## Environment

Flipper Desktop version: 0.78.0
Connected with android emulator : Nexus_5_api_29
```
Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.

Component stack:

    at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1167)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.ScrollContainer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1942)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at e.LeftSidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4728:529)
    at AppInspect (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4727:136)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1333:1802)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at GutterWrapper (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:3286)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Interactive (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:2848:752)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Sidebar (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3047:1924)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1836)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1339:1754)
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:67:145)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:16:913
    at ContextMenuProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:62:1195)
    at PopoverProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4718:132)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3018:3008)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:29:917)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3:941)

Error stacktrace:
Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
    at Object.getState (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:42:3147)
    at useSelectorWithStoreAndSubscription (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:56:776)
    at useSelector (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:56:1368)
    at useStore (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3275:175)
    at PluginList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4730:1244)
    at Ch (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:59074)
    at li (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:68595)
    at ki (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:67929)
    at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:114774)
    at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98507)
    at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98435)
    at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:98298)
    at Lj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:95289)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44912
    at e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:61:3794)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44689)
    at jg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44857)
    at ig (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:44792)
    at Jg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:92663)
    at Oh (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:59:64370)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1329:1037
    at Array.forEach (<anonymous>)
    at AtomValue.notifyChanged (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1329:1026)
    at AtomValue.set (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1329:922)
    at MetroDevice.disconnect (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3377:3059)
    at MetroDevice.destroy (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3377:3082)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:2481
    at Proxy.filter (<anonymous>)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:2450
    at _e194.W.produce (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:69:14330)
    at e.default (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:2423)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4094:2253
    at combination (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:42:2287)
    at rootReducer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4139:482)
    at Object.dispatch (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:42:4480)
    at unregisterDevices (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4782:1449)
    at WebSocket.n.onclose.n.onerror (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4782:1508)
```

**Comment by mweststrate** [comment]
Reproduced, will be fixed in 0.79
