### ISSUE TITLE
Does not work with adb network connections

### ISSUE THREAD

**Issue by tmm1** [facebook/flipper#206]
I have several Android TV devices which I connect to over the network with adb.

```
$ adb devices -l
List of devices attached
10.0.1.180:5555        device product:stark model:AFTA device:stark transport_id:5
10.0.1.182:5555        device product:foster_e model:SHIELD_Android_TV device:foster transport_id:3
```

Flipper uses `adb reverse tcp:8088 tcp:8088` which only works with USB connected devices:

```
$ adb -s 10.0.1.182 reverse tcp:8089 tcp:8089
error: more than one device/emulator
```

which I also see in the app:

```
Unhandled rejection FailError: Failure: 'more than one device/emulator'
    at http://localhost:3001/src/init.bundle:59058:31
From previous event:
    at Parser.readError (http://localhost:3001/src/init.bundle:59057:31)
    at http://localhost:3001/src/init.bundle:61970:41
From previous event:
    at http://localhost:3001/src/init.bundle:61964:48
From previous event:
    at ReverseCommand.execute (http://localhost:3001/src/init.bundle:61960:39)
    at http://localhost:3001/src/init.bundle:51808:46
From previous event:
    at Client.reverse (http://localhost:3001/src/init.bundle:51807:37)
    at AndroidDevice.reverse (http://localhost:3001/src/init.bundle:49002:25)
    at client.getProperties.then (http://localhost:3001/src/init.bundle:91029:23)
From previous event:
    at Promise (http://localhost:3001/src/init.bundle:91021:39)
    at new Promise (<anonymous>)
    at createDecive (http://localhost:3001/src/init.bundle:91019:12)
    at Tracker.tracker.on (http://localhost:3001/src/init.bundle:91081:39)
    at Tracker.emit (events.js:182:13)
    at Tracker.update (http://localhost:3001/src/init.bundle:60559:16)
    at http://localhost:3001/src/init.bundle:60532:17
From previous event:
    at Tracker.read (http://localhost:3001/src/init.bundle:60530:56)
    at new Tracker (http://localhost:3001/src/init.bundle:60512:26)
    at http://localhost:3001/src/init.bundle:60463:22
    at process._tickCallback (internal/process/next_tick.js:68:7)
From previous event:
    at HostTrackDevicesCommand.execute (http://localhost:3001/src/init.bundle:60459:39)
    at http://localhost:3001/src/init.bundle:51727:50
From previous event:
    at Client.trackDevices (http://localhost:3001/src/init.bundle:51726:32)
    at _default (http://localhost:3001/src/init.bundle:91063:12)
    at forEach.fn (http://localhost:3001/src/init.bundle:90998:154)
    at Array.forEach (<anonymous>)
    at _default (http://localhost:3001/src/init.bundle:90998:140)
    at http://localhost:3001/src/init.bundle:330:23
    at loadModuleImplementation (http://localhost:3001/src/init.bundle:157:7)
    at guardedLoadModule (http://localhost:3001/src/init.bundle:90:14)
    at require (http://localhost:3001/src/init.bundle:71:62)
    at http://localhost:3001/src/init.bundle:95985:1
```

**Comment by jknoxville** [comment]
Thanks for the report, I just tried this out of curiosity, and I'm also hitting the same thing. Here's the google bug tracker link for the adb reverse issue: https://issuetracker.google.com/issues/37066218

If anyone is interested in building a workaround to avoid having to use adb reverse, you could try to figure out the ip address of the host computer that flipper is running on, and then connect straight to that, instead of localhost, from the device.

As for how you could find out the IP address, it would be a bit long-winded, but one method would be to get flipper desktop to write its local IP address into a file in the flipper-enabled app using adb shell, in a similar way to how the certificate exchange currently works.
