### ISSUE TITLE
unit test with flipper crashes on SoLoader.init()

### ISSUE THREAD

**Issue by lannyf77** [facebook/flipper#2075]
Using the flipper in an android library project, having a optionalDependencies class (for only using flipper in debug)  used to be for getting `StethoInterceptor` and now change to return FlipperOkhttpInterceptor(networkPlugin). It has been running  fine with the app.

And this is the only change for replacing stetho with flipper.

```
public class OptionalDependenciesImpl implements OptionalDependencies {
    private Interceptor stethoInterceptor = null;
    private static OptionalDependenciesImpl instance;

    private OptionalDependenciesImpl(Context context){
        if (FlipperUtils.shouldEnableFlipper(context)) {

            SoLoader.init(context, false);  //<=== throws in unit test

            NetworkFlipperPlugin networkPlugin = new NetworkFlipperPlugin();
            final FlipperClient client = AndroidFlipperClient.getInstance(context);
            client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
            client.addPlugin(networkPlugin);
            client.start();

            // was             stethoInterceptor = new StethoInterceptor();  //

            stethoInterceptor = new FlipperOkhttpInterceptor(networkPlugin);
        }
    }

    public static synchronized OptionalDependenciesImpl getInstance(Context context){
        if (instance == null){
            instance = new OptionalDependenciesImpl(context);
        }
        return instance;
    }

    @Nullable
    @Override
    public Interceptor getFbflipperInterceptor() {
        return fbflipperInterceptor;
    }
}
```

in the unit test start up, the `TheNetworkAPI.init(application)` will call into `createOkHttpClient` and `OptionalDependenciesImpl`

```
@RunWith(RobolectricTestRunner.class)
...
    @Before
    public void setUp() throws Exception {
        application = ApplicationProvider.getApplicationContext();
        ...
        ///
        //SoLoader ???
        ///

        // init network
        TheNetworkAPI.init(application);
       ...
    }
```
and return the OkHttpClient to  be used in the test (and in the app)
```
private OkHttpClient createOkHttpClient(Context context) {
        OptionalDependencies stethoOption = OptionalDependenciesImpl.getInstance(context);
        Interceptor stethorInterceptor = stethoOption.getFbflipperInterceptor();
        return getOkHttpClient(context, stethorInterceptor);
    }
@VisibleForTesting
    OkHttpClient getOkHttpClient(Context context, @Nullable Interceptor networkInterceptor) {
        List<Interceptor> interceptors = new ArrayList<>();
        interceptors.add(TelemetryLogInterceptor.create(context, 0));
        long cacheSize = context.getResources().getInteger(R.integer.shadowfax_okhttp_cache_size);
        Cache cache = new Cache(context.getCacheDir(), cacheSize);
        if (networkInterceptor != null) {
            return YOkHttp.create(interceptors).newBuilder()
                    .addNetworkInterceptor(networkInterceptor).cache(cache).build();
        } else {
            return YOkHttp.create(interceptors).newBuilder().cache(cache).build();
        }
    }
```

when run the test,  it throws exception at `SoLoader.init` in the `OptionalDependenciesImpl`
```
        java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at com.facebook.soloader.ApplicationSoSource.<init>(ApplicationSoSource.java:46)
        at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:285)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:207)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:189)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:217)
        at com.mobile.app.OptionalDependenciesImpl.<init>(OptionalDependenciesImpl.java:24)
        at com.mobile.app.OptionalDependenciesImpl.getInstance(OptionalDependenciesImpl.java:36)
        at com.mobile.app.TheNetworkAPI.createOkHttpClient(TheNetworkAPI.java:93)
        at com.mobile.app.TheNetworkAPI.<init>(TheNetworkAPI.java:56)
        at com.mobile.app.TheNetworkAPI.createInstance(TheNetworkAPI.java:61)
        at com.mobile.app.TheNetworkAPI.init(TheNetworkAPI.java:67)
        at com.mobile.app.BaseTest.setUp(BaseTest.java:39)
```

if comment out the line `SoLoader.init(context, false);` in the `OptionalDependenciesImpl`, then it got:
```
[Robolectric] com.oath.mobile.app.OptionalDependenciesTest.testConstructors: sdk=27; resources=BINARY
Exception in thread "FlipperEventBaseThread" Exception in thread "FlipperConnectionThread" java.lang.ExceptionInInitializerError
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
Caused by: java.lang.IllegalStateException: NativeLoader has not been initialized.  To use standard native library loading, call NativeLoader.init(new SystemDelegate()).
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:45)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
	at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
	... 1 more
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.flipper.android.EventBase
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

What need to do in the unit test when using flipper?

**Comment by lannyf77** [comment]
looks like similar to https://github.com/facebook/flipper/issues/1531
but after add the 
```
import android.app.Application;

class TestApplication extends Application {}
```
and `@Config(application = TestApplication.class)`
```
@RunWith(RobolectricTestRunner.class)
@Config(application = TestApplication.class)
public abstract class BaseTest {
    protected Application application;
    ...
   @Before
    public void setUp() throws Exception {
        application = ApplicationProvider.getApplicationContext();
        ...
        ///
        //SoLoader ???
        ///

        // init network
        TheNetworkAPI.init(application);
       ...
    }
```
still get same cash `at com.facebook.soloader.ApplicationSoSource.<init>(ApplicationSoSource.java:46)`

**Comment by lannyf77** [comment]
when running the app it is fine and this this.applicationContext.getApplicationInfo().nativeLibraryDir has
```
/data/app/com.mobile.app.prod-0cPO_yP1A_AXN0Z4Dn6TSA==/lib/x86
```
but when in the test the nativeLibraryDir is null
```
public ApplicationSoSource(Context context, int flags) {
    this.applicationContext = context.getApplicationContext();
    if (this.applicationContext == null) {
        Log.w("SoLoader", "context.getApplicationContext returned null, holding reference to original context.");
        this.applicationContext = context;
    }

    this.flags = flags;
    this.soSource = new DirectorySoSource(new File(this.applicationContext.getApplicationInfo().nativeLibraryDir), flags);
}


/data/app/com.mobile.app.prod-0cPO_yP1A_AXN0Z4Dn6TSA==/lib/x86
```

**Comment by lannyf77** [comment]
it could be also reproduced with [flipper sample code](https://github.com/facebook/flipper/blob/0b2e5f645467bd0ee886d651ebf9cc7e5752ffbc/android/sample/src/test/java/com/facebook/flipper/plugins/example/ExampleFlipperPluginTest.java)

adding the `SoLoader.init(application, false);`
```
@RunWith(RobolectricTestRunner.class)
@Config(application = TestApplication.class)
public class ExampleFlipperPluginTest {

  @Test
  public void greetingTest() throws Exception {
    final ExampleFlipperPlugin plugin = new ExampleFlipperPlugin();
    final FlipperConnectionMock connection = new FlipperConnectionMock();
    final FlipperResponderMock responder = new FlipperResponderMock();

    //
    SoLoader.init(application, false);

    plugin.onConnect(connection);
    connection
        .receivers
        .get("displayMessage")
        .onReceive(new FlipperObject.Builder().put("message", "test").build(), responder);

    assertThat(
        responder.successes, hasItem(new FlipperObject.Builder().put("greeting", "Hello").build()));
  }
}
```

![image](https://user-images.githubusercontent.com/19765258/111623944-7073b080-87c1-11eb-96bb-3cb45297822b.png)

**Comment by passy** [comment]
I think you're approach of running against Flipper mocks makes sense. Loading the native library as part of your unit tests is probably not a great idea. So I would go further and remove the `SoLoading` bit from your test application and mock out all pieces that make use of native calls.

**Comment by priteshrnandgaonkar** [comment]
Does the above recommendation from @passy solve the problem ?
