### ISSUE TITLE
Crash on SoLoader.init() Samsung Galaxy S9 Only

### ISSUE THREAD

**Issue by joel-kenny** [facebook/flipper#2213]
## 🐛 Bug Report
This only happens on one phone, which happens to be a Samsung Galaxy S9 that previously had no problem. It started happening today and seems to be related to that specific phone. Old app versions that worked before no longer work. It appears that the app no longer has permission to access the lock file. Tried giving it permission to write external storage but that had no effect.

```
FATAL EXCEPTION: main
Process: <application_id>, PID: 2497
java.lang.RuntimeException: Unable to create application <application_class_name>: java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/<application_id>/lib-main/dso_lock: open failed: EACCES (Permission denied)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7150)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7095)
       at android.app.ActivityThread.access$1700(ActivityThread.java:273)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8125)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/<application_id>/lib-main/dso_lock: open failed: EACCES (Permission denied)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:219)
       at com.<app_package>.utils.FlipperHelper.enableFlipper(FlipperHelper.kt:19)
       at com.<application_class_name>.onCreate(AvaApp.kt:100)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7145)
       ... 9 more
Caused by: java.io.FileNotFoundException: /data/user/0/<application_id>/lib-main/dso_lock: open failed: EACCES (Permission denied)
       at libcore.io.IoBridge.open(IoBridge.java:496)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
       at com.facebook.soloader.FileLocker.<init>(FileLocker.java:36)
       at com.facebook.soloader.FileLocker.lock(FileLocker.java:32)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:430)
       at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:327)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:207)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:189)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:217)
       ... 13 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
       at libcore.io.Linux.open(Native Method)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8002)
       at libcore.io.IoBridge.open(IoBridge.java:482)
```

## To Reproduce
Start the app. It crashes immediately.

## Environment
Android 10
Samsung Galaxy S9

**Comment by commonsguy** [comment]
Teammates have also run into this on a Pixel 4 and a Pixel 3 XL, so it is not specific to the Galaxy S9. We have not been able to isolate steps to reproduce the problem.

**Comment by joel-kenny** [comment]
@commonsguy that makes sense. Somehow the application does not have permission to access the lock file.

**Comment by zakrodionov** [comment]
Same error on v0.91.1 Poco X3

**Comment by rodinhatokay** [comment]
I'm having this issue with OnePlus 8T

**Comment by mweststrate** [comment]
We cannot really debug this from just a stack trace. I'd recommend to try running the flipper sample applications as can be found in this repo, and work from there.

**Comment by yifeifiona** [comment]
Same on Samsung Galaxy S9+

**Comment by jamsch** [comment]
Update for React Native users: It seems that React Native (ReactActivity) calls SoLoader as well. So you'll likely need to set the file permissions before calling `super.onCreate();`

https://github.com/facebook/react-native/blob/ce74aa4ed335d4c36ce722d47937b582045e05c4/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L398-L407

```
Caused by: java.io.FileNotFoundException: 
  at libcore.io.IoBridge.open (IoBridge.java:492)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:236)
  at java.io.FileOutputStream.<init> (FileOutputStream.java:186)
  at com.facebook.soloader.FileLocker.<init> (FileLocker.java:36)
  at com.facebook.soloader.FileLocker.lock (FileLocker.java:32)
  at com.facebook.soloader.UnpackingSoSource.prepare (UnpackingSoSource.java:430)
  at com.facebook.soloader.SoLoader.initSoSources (SoLoader.java:327)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:207)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:189)
  at com.facebook.soloader.SoLoader.init (SoLoader.java:217)
  at com.facebook.react.ReactInstanceManager.initializeSoLoaderIfNecessary (ReactInstanceManager.java:360)
  at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory (ReactInstanceManagerBuilder.java:296)
  at com.facebook.react.ReactInstanceManagerBuilder.build (ReactInstanceManagerBuilder.java:270)
  at com.facebook.react.ReactNativeHost.createReactInstanceManager (ReactNativeHost.java:87)
  at com.facebook.react.ReactNativeHost.getReactInstanceManager (ReactNativeHost.java:39)
  at com.facebook.react.ReactDelegate.loadApp (ReactDelegate.java:104)
  at com.facebook.react.ReactActivityDelegate.loadApp (ReactActivityDelegate.java:90)
  at com.facebook.react.ReactActivityDelegate.onCreate (ReactActivityDelegate.java:85)
  at com.facebook.react.ReactActivity.onCreate (ReactActivity.java:45)
  at com.example.app.MainActivity.onCreate (MainActivity.java:28)
```

**Comment by aman32767** [comment]
In our case, the build version code is causing the issue. 

Its was sorted till 407 but after that 408, 409 .. are causing crash. 

We are building version code for variant releases at run time which is crossing some kind of limit.

Will update further in this group
