### ISSUE TITLE
Flipper overheat MacBook Pro (Mac OS 11.3)

### ISSUE THREAD

**Issue by magrinj** [facebook/flipper#2346]
## 🐛 Bug Report

Each time I'm running `Flipper` on my Mac linked to a simulator or a physical device, my Mac start to overheat and the fan go to max speed.
It only happen when Flipper is opened, with or without plugins.

## To Reproduce
Just run Flipper on Mac OS.

## Environment
Mac OS 11.3 (20E232)
MacBook Pro (16-inch, 2019)
Processor 2.6 GHz 6-Core Intel Core i7
Memory 16 GB 2667 MHz DDR4

**Comment by mweststrate** [comment]
This is often a symptom if idb is not set up correctly: https://www.internalfb.com/intern/staticdocs/flipper/docs/extending/desktop-plugin-structure#adding-fb-only-code-to-open-sourced-plugins

**Comment by nikoant** [comment]
Hey @mweststrate, looks like you posted a wrong link

**Comment by mweststrate** [comment]
woops, updated

**Comment by magrinj** [comment]
@mweststrate Thanks for the help !
Looks like I have a problem with `idb`.
I'm actually trying to reinstall  `idb` and `idb-companion` on my machine, but not really working for the time.
I've the following error with `idb list-targets`:

```
2021-05-21 13:53:06,485 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/companion.py", line 71, in parse_json_line
    return json.loads(decoded_line)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/companion_spawner.py", line 153, in spawn_notifier
    await self._read_notifier_output(stream=none_throws(process.stdout))
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/companion_spawner.py", line 166, in _read_notifier_output
    update = parse_json_line(line)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/companion.py", line 73, in parse_json_line
    raise IdbJsonException(f"Failed to parse json from: {decoded_line}")
idb.common.companion.IdbJsonException: Failed to parse json from:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/cli/main.py", line 287, in gen_main
    await root_command.run(args)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/command.py", line 90, in run
    return await self.resolve_command_from_args(args).run(args)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/cli/__init__.py", line 106, in run
    await self._run_impl(args)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/cli/__init__.py", line 150, in _run_impl
    args=args, manager=_get_management_client(logger=self.logger, args=args)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/cli/commands/target.py", line 171, in run_with_manager
    targets = await manager.list_targets()
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/logging.py", line 113, in _async_wrapper
    raise ex
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/logging.py", line 88, in _async_wrapper
    value = await function(*args, **kwargs)
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/grpc/management.py", line 135, in list_targets
    await self._spawn_notifier()
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/grpc/management.py", line 57, in _spawn_notifier
    await companion_spawner.spawn_notifier()
  File "/Users/magrin_j/.pyenv/versions/3.7.10/lib/python3.7/site-packages/idb/common/companion_spawner.py", line 159, in spawn_notifier
    ) from e
idb.common.companion_spawner.CompanionSpawnerException: Failed to spawn the idb notifier. Stderr: dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc++.1.dylib

  Referenced from: /usr/local/bin/idb_companion

  Reason: image not found
```

**Comment by mweststrate** [comment]
That looks a lot like https://github.com/facebook/idb/issues/671

**Comment by magrinj** [comment]
@mweststrate Thanks, yes it's the same error !
Sounds maybe related to last Mac OS update 🤔

**Comment by L-Yeiser** [comment]
@magrinj when your mac starts to overheat are you seeing a massive spike in the `kernal_task` usage of CPU. My computer has been slowing down over the last few months and after I upgraded my OS I cannot run flipper and xCode without massive issue.

**Comment by magrinj** [comment]
@L-Yeiser No I don't see any `kernel_task` at the time, and no massive spike when running flipper and a simulator.

But I saw this post on stack exchange that should help you: https://apple.stackexchange.com/questions/363337/how-to-find-cause-of-high-kernel-task-cpu-usage

Apparently high `kernel_task` is due to **high chassis temperature**...
And plugging the power adapter on the right side can reduce this apparently 🤯

**Comment by nikoant** [comment]
Looks like now we're discussing another issue :)

**Comment by magrinj** [comment]
@mweststrate You got it right, after upgrading `idb` to latest release that fix issue with latest Mac OS, `idb` is now working properly and Flipper stop overheating my Mac ! Thanks for the help and pointing the direction where to look !
