### ISSUE TITLE
Question: I've the following error with idb list-targets

### ISSUE THREAD

**Issue by khanhduy62** [facebook/flipper#2380]
Please help me, I've the following error with `idb list-targets`
node: v10.13.0
macOS Big Sur version 11.4 (Macbook Pro 2018)
xcode 12.5

```
~ idb list-targets
2021-05-30 14:27:45,308 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/idb/common/companion.py", line 71, in parse_json_line
return json.loads(decoded_line)
File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/idb/common/companion_spawner.py", line 153, in spawn_notifier
await self._read_notifier_output(stream=none_throws(process.stdout))
File "/usr/local/lib/python3.9/site-packages/idb/common/companion_spawner.py", line 166, in _read_notifier_output
update = parse_json_line(line)
File "/usr/local/lib/python3.9/site-packages/idb/common/companion.py", line 73, in parse_json_line
raise IdbJsonException(f"Failed to parse json from: {decoded_line}")
idb.common.companion.IdbJsonException: Failed to parse json from:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/idb/cli/main.py", line 287, in gen_main
await root_command.run(args)
File "/usr/local/lib/python3.9/site-packages/idb/common/command.py", line 90, in run
return await self.resolve_command_from_args(args).run(args)
File "/usr/local/lib/python3.9/site-packages/idb/cli/init.py", line 106, in run
await self._run_impl(args)
File "/usr/local/lib/python3.9/site-packages/idb/cli/init.py", line 149, in _run_impl
await self.run_with_manager(
File "/usr/local/lib/python3.9/site-packages/idb/cli/commands/target.py", line 171, in run_with_manager
targets = await manager.list_targets()
File "/usr/local/lib/python3.9/site-packages/idb/common/logging.py", line 113, in _async_wrapper
raise ex
File "/usr/local/lib/python3.9/site-packages/idb/common/logging.py", line 88, in _async_wrapper
value = await function(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/idb/grpc/management.py", line 135, in list_targets
await self._spawn_notifier()
File "/usr/local/lib/python3.9/site-packages/idb/grpc/management.py", line 57, in _spawn_notifier
await companion_spawner.spawn_notifier()
File "/usr/local/lib/python3.9/site-packages/idb/common/companion_spawner.py", line 156, in spawn_notifier
raise CompanionSpawnerException(
idb.common.companion_spawner.CompanionSpawnerException: Failed to spawn the idb notifier. Stderr: dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found

dyld: Library not loaded: /usr/local/opt/grpc/lib/libgrpc.15.dylib

Referenced from: /usr/local/bin/idb_companion

Reason: image not found
```

**Comment by passy** [comment]
We're not maintaining that tool. Can you please open that issue with the folks over at https://github.com/facebook/idb?
