### ISSUE TITLE
Could not find com.facebook.fresco:flipper:2.4.0.

### ISSUE THREAD

**Issue by meftunca** [facebook/flipper#2410]
## 🐛 Bug Report
```
yarn run v1.22.10
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1860 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_app package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_analytics:firebase.bom using default value: 28.0.1
:react-native-firebase_analytics package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_analytics:version set from package.json: 12.0.0 (12,0,0 - 12000000)
:react-native-firebase_analytics:android.compileSdk using custom value: 29
:react-native-firebase_analytics:android.targetSdk using custom value: 29
:react-native-firebase_analytics:android.minSdk using custom value: 21
:react-native-firebase_analytics:reactNativeAndroidDir /Users/devloops/Desktop/maple/mobile/node_modules/react-native/android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using default value: 28.0.1
:react-native-firebase_app:play.play-services-auth using default value: 19.0.0
:react-native-firebase_app package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 12.0.0 (12,0,0 - 12000000)
:react-native-firebase_app:android.compileSdk using custom value: 29
:react-native-firebase_app:android.targetSdk using custom value: 29
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir /Users/devloops/Desktop/maple/mobile/node_modules/react-native/android

> Configure project :react-native-firebase_crashlytics
:react-native-firebase_crashlytics package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/crashlytics/package.json
:react-native-firebase_app package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_crashlytics:firebase.bom using default value: 28.0.1
:react-native-firebase_crashlytics package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/crashlytics/package.json
:react-native-firebase_crashlytics:version set from package.json: 12.0.0 (12,0,0 - 12000000)
:react-native-firebase_crashlytics:android.compileSdk using custom value: 29
:react-native-firebase_crashlytics:android.targetSdk using custom value: 29
:react-native-firebase_crashlytics:android.minSdk using custom value: 21
:react-native-firebase_crashlytics:reactNativeAndroidDir /Users/devloops/Desktop/maple/mobile/node_modules/react-native/android

> Configure project :react-native-firebase_in-app-messaging
:react-native-firebase_in-app-messaging package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/in-app-messaging/package.json
:react-native-firebase_app package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_in-app-messaging:firebase.bom using default value: 28.0.1
:react-native-firebase_in-app-messaging package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/in-app-messaging/package.json
:react-native-firebase_in-app-messaging:version set from package.json: 12.0.0 (12,0,0 - 12000000)
:react-native-firebase_in-app-messaging:android.compileSdk using custom value: 29
:react-native-firebase_in-app-messaging:android.targetSdk using custom value: 29
:react-native-firebase_in-app-messaging:android.minSdk using custom value: 21
:react-native-firebase_in-app-messaging:reactNativeAndroidDir /Users/devloops/Desktop/maple/mobile/node_modules/react-native/android

> Configure project :react-native-firebase_messaging
:react-native-firebase_messaging package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_app package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_messaging:firebase.bom using default value: 28.0.1
:react-native-firebase_messaging package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/messaging/package.json
:react-native-firebase_messaging:version set from package.json: 12.0.0 (12,0,0 - 12000000)
:react-native-firebase_messaging:android.compileSdk using custom value: 29
:react-native-firebase_messaging:android.targetSdk using custom value: 29
:react-native-firebase_messaging:android.minSdk using custom value: 21
:react-native-firebase_messaging:reactNativeAndroidDir /Users/devloops/Desktop/maple/mobile/node_modules/react-native/android

> Configure project :react-native-firebase_perf
:react-native-firebase_perf package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/perf/package.json
:react-native-firebase_app package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_perf:firebase.bom using default value: 28.0.1
:react-native-firebase_perf package.json found at /Users/devloops/Desktop/maple/mobile/node_modules/@react-native-firebase/perf/package.json
:react-native-firebase_perf:version set from package.json: 12.0.0 (12,0,0 - 12000000)
:react-native-firebase_perf:android.compileSdk using custom value: 29
:react-native-firebase_perf:android.targetSdk using custom value: 29
:react-native-firebase_perf:android.minSdk using custom value: 21
:react-native-firebase_perf:reactNativeAndroidDir /Users/devloops/Desktop/maple/mobile/node_modules/react-native/android

> Configure project :terrylinla_react-native-sketch-canvas
WARNING:: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :lottie-react-native
WARNING:: The specified Android SDK Build Tools version (29.0.3) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.1.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '29.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-pager-view', ':react-native-webview'
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-action-sheet', project ':react-native-camera', project ':react-native-community_async-storage', ...

> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
74 actionable tasks: 74 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.fresco:flipper:2.4.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - file:/Users/devloops/.m2/repository/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - https://www.jitpack.io/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - https://maven.google.com/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.92.0
   > Could not find com.facebook.fresco:stetho:2.4.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - file:/Users/devloops/.m2/repository/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - https://www.jitpack.io/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - https://maven.google.com/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.92.0
   > Could not find com.facebook.yoga:proguard-annotations:1.14.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - file:/Users/devloops/.m2/repository/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - https://www.jitpack.io/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - https://maven.google.com/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
     Required by:
         project :app > com.facebook.react:react-native:0.64.1
   > Could not find com.facebook.fbjni:fbjni-java-only:0.0.3.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - file:/Users/devloops/.m2/repository/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - https://www.jitpack.io/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - https://maven.google.com/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
     Required by:
         project :app > com.facebook.react:react-native:0.64.1
   > Could not find com.yqritc:android-scalablevideoview:1.0.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - file:/Users/devloops/.m2/repository/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://dl.google.com/dl/android/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://www.jitpack.io/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://maven.google.com/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
     Required by:
         project :app > project :react-native-video

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 1m 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.facebook.fresco:flipper:2.4.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - file:/Users/devloops/.m2/repository/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - https://www.jitpack.io/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
       - https://maven.google.com/com/facebook/fresco/flipper/2.4.0/flipper-2.4.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.92.0
   > Could not find com.facebook.fresco:stetho:2.4.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - file:/Users/devloops/.m2/repository/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - https://www.jitpack.io/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
       - https://maven.google.com/com/facebook/fresco/stetho/2.4.0/stetho-2.4.0.pom
     Required by:
         project :app > com.facebook.flipper:flipper-fresco-plugin:0.92.0
   > Could not find com.facebook.yoga:proguard-annotations:1.14.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - file:/Users/devloops/.m2/repository/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - https://www.jitpack.io/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
       - https://maven.google.com/com/facebook/yoga/proguard-annotations/1.14.1/proguard-annotations-1.14.1.pom
     Required by:
         project :app > com.facebook.react:react-native:0.64.1
   > Could not find com.facebook.fbjni:fbjni-java-only:0.0.3.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - file:/Users/devloops/.m2/repository/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - https://dl.google.com/dl/android/maven2/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - https://www.jitpack.io/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
       - https://maven.google.com/com/facebook/fbjni/fbjni-java-only/0.0.3/fbjni-java-only-0.0.3.pom
     Required by:
         project :app > com.facebook.react:react-native:0.64.1
   > Could not find com.yqritc:android-scalablevideoview:1.0.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - file:/Users/devloops/.m2/repository/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/react-native/android/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - file:/Users/devloops/Desktop/maple/mobile/node_modules/jsc-android/dist/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://dl.google.com/dl/android/maven2/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://www.jitpack.io/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
       - https://maven.google.com/com/yqritc/android-scalablevideoview/1.0.4/android-scalablevideoview-1.0.4.pom
     Required by:
         project :app > project :react-native-video

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 1m 7s

    at makeError (/Users/devloops/Desktop/maple/mobile/node_modules/execa/index.js:174:9)
    at /Users/devloops/Desktop/maple/mobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/devloops/Desktop/maple/mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/devloops/Desktop/maple/mobile/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## To Reproduce
I tried all versions up to 75 but I couldn't get a successful compilation.
When compiling, I cannot get the relevant packages from the remote server. So I can't start build on android
## Environment

```
System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 196.04 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

**Comment by Warmachine13** [comment]
Same error after upgrade react native from 0.64.2 to 0.65.1 on npm react-native run android

**Comment by Rc85** [comment]
Did you fix this? I am getting this error if I am using mavenCentral and running in development. If I use jcenter, all is good. But jcenter is being removed soon.
