### ISSUE TITLE
Flipper crash

### ISSUE THREAD

**Issue by har2008preet** [facebook/flipper#2437]
## 🐛 Bug Report

```
Error: ENOENT: no such file or directory, open 'C:\Users\Harpreet Singh\Downloads\static\icons.json'

Flipper version: 0.0.0

Component stack:

    at Glyph (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:3322:1277)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at AppIcon (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:5383:2460)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at button
    at Wave (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:380:1518)
    at InternalButton (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:377:2814)
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at Trigger (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:302:1934)
    at Dropdown (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:369:1167)
    at Dropdown (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:367:1343)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2082:1280
    at AppSelector (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:5383:691)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at Layout.Top (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2952:3437)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at LeftSidebar (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:5382:377)
    at AppInspect (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:5381:925)
    at TrackingScope (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2930:1646)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at Layout.Right (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2952:3581)
    at GutterWrapper (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2953:3242)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at Interactive (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2954:782)
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at Sidebar (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2953:1827)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at Layout.Left (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2952:3535)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at Layout.Top (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:2952:3437)
    at SandyApp (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:105:1382)
    at div
    at file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:31:703
    at ContextMenuProvider (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:101:1309)
    at PopoverProvider (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:5373:2786)
    at TooltipProvider (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:3388:2112)
    at Provider (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:52:1038)
    at AppFrame (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:3:1244)

Error stacktrace:
Error: ENOENT: no such file or directory, open 'C:\Users\Harpreet Singh\Downloads\static\icons.json'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
    at getIcons (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:3323:674)
    at buildIconURL (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:3323:1416)
    at getIconURL (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:3323:2542)
    at Glyph.render (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:3322:1517)
    at qi (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:73994)
    at pi (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:73788)
    at Bl (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:110418)
    at bk (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:101446)
    at ak (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:101374)
    at Tj (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:101227)
    at Lj (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:98001)
    at Jg (file:///C:/Users/Harpreet%20Singh/Downloads/Flipper-win%20(1)/resources/app.asar/bundle.js:89:95524)
```

## To Reproduce

Opens the application

## Environment

running android application, Android 12 beta 2. flipper: 0.93.0 windows application

**Comment by har2008preet** [comment]
extracting in different drive solves the issue
