### ISSUE TITLE
React-navigation plugin crashes Flipper

### ISSUE THREAD

**Issue by AmirNexter** [facebook/flipper#2575]
## 🐛 Bug Report
Flipper is crashing with the following report: 

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20Minified%20React%20error%20%23130%3B%20visit%20https%3A%2F%2Freactjs.org%2Fdocs%2Ferror-decoder.html%3Finvariant%3D130%26args%5B%5D%3Dundefined%26args%5B%5D%3D%20for%20the%20full%20message%20or%20use%20the%20non-minified%20dev%20environment%20for%20full%20errors%20and%20additional%20helpful%20warnings. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Flipper version: 0.96.1

Component stack:

    at pre
    at div
    at Typography (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1060:1471)
    at ResizeObserver (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:126:1432)
    at LocaleReceiver (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:178:1334)
    at Base (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1062:2779)
    at Paragraph
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at CodeBlock (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3364:294)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at ErrorBoundary (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3419:1660)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at Layout.Right (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1535:3581)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1535:3437)
    at PluginContainer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4533:2045)
    at Connect(PluginContainer) (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:60:3004)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1535:3535)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at Layout.Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1535:3437)
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:105:1382)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:31:703
    at ContextMenuProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:101:1309)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3427:2112)
    at PersistGate (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5658:2634)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:52:1038)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3:1250)

Error stacktrace:
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Error%3A%20Minified%20React%20error%20%23130%3B%20visit%20https%3A%2F%2Freactjs.org%2Fdocs%2Ferror-decoder.html%3Finvariant%3D130%26args%5B%5D%3Dundefined%26args%5B%5D%3D%20for%20the%20full%20message%20or%20use%20the%20non-minified%20dev%20environment%20for%20full%20errors%20and%20additional%20helpful%20warnings. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Rg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:53243)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:58166
    at fi (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:69374)
    at Bl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:111140)
    at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:101446)
    at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:101374)
    at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:101227)
    at Lj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:98001)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:46741
    at _e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:100:3887)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:46516)
    at jg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:46686)
    at ig (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:46619)
    at Wj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:89:98439)
    at Client.flushMessageBuffer (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4054:1431)
    at invokeFunc (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3316:64526)

## To Reproduce
I bumped react-navigation to V6 with all the necessary changes according to their docs. 
Installed react-navigation/devtools and used the useFlipper hook with the navigation ref.

In Flipper / react navigation plugin  - you get a massage "Navigate in the app to see actions"
After a navigate action, Flipper crashes with the above crash report. 

## Environment

Flipper - Version 0.96.1 (50.0.0)

    "@react-navigation/devtools": "^6.0.0-next.16",
    "@react-navigation/native": "^6.0.0-next.15",
    "@react-navigation/native-stack": "^6.0.0-next.9",
    "react": "17.0.1",
    "react-native": "0.64.1",

**Comment by mweststrate** [comment]
The above error should be fixed by https://github.com/facebook/flipper/commit/88d6d000c83e9b2d6f04e5501e1f5032452286ab (should be released later today), however there is probably an underlying error as well, that should appear in the console logs.
