### ISSUE TITLE
createTablePlugin is not a function

### ISSUE THREAD

**Issue by Dkhusainov** [facebook/flipper#2611]
## 🐛 Bug Report

```
Plugin query failed to load TypeError: (0 , _flipper.createTablePlugin) is not a function
    at C:\Users\mole\.flipper\installed-plugins\flipper-plugin-query\1.0.0\dist\bundle.js:789:49

    at loadModuleImplementation (C:\Users\mole\.flipper\installed-plugins\flipper-plugin-query\1.0.0\dist\bundle.js:286:7)

    at guardedLoadModule (C:\Users\mole\.flipper\installed-plugins\flipper-plugin-query\1.0.0\dist\bundle.js:166:14)

    at metroRequire (C:\Users\mole\.flipper\installed-plugins\flipper-plugin-query\1.0.0\dist\bundle.js:93:75)

    at Object.<anonymous> (C:\Users\mole\.flipper\installed-plugins\flipper-plugin-query\1.0.0\dist\bundle.js:799:25)

    at Object.<anonymous> (C:\Users\mole\.flipper\installed-plugins\flipper-plugin-query\1.0.0\dist\bundle.js:801:3)

    at Module._compile (internal/modules/cjs/loader.js:1152:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)

    at Module.load (internal/modules/cjs/loader.js:992:32)

    at Module._load (internal/modules/cjs/loader.js:885:14)

    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)

    at Module.require (internal/modules/cjs/loader.js:1032:19)

    at require (internal/modules/cjs/helpers.js:72:18)

    at requirePluginInternal (file:///Z:/flipper/resources/app.asar/bundle.js:3823:5690)

    at file:///Z:/flipper/resources/app.asar/bundle.js:3823:5529

    at tryCatchReportPluginFailures (file:///Z:/flipper/resources/app.asar/bundle.js:3688:1493)
```
## To Reproduce

1. Use `flipper-pkg init` to bootstrap the plugin 
2. Delete `flipper-plugin` from `package.json`
3. Create an empty table plugin as described in https://fbflipper.com/docs/extending/create-table-plugin/

## Environment

Flipper: 0.98.0

**Comment by mweststrate** [comment]
Hey @Dkhusainov, apologies for the inconvenience! The page you're linking to is deprecated, but the up to date tutorial is here: https://fbflipper.com/docs/tutorial/js-table, with the full options documented here: 

https://fbflipper.com/docs/extending/flipper-plugin#createtableplugin. Note that imports come from `flipper-plugin`, not `flipper` in the updated tutorials / APIs.

**Comment by Dkhusainov** [comment]
Reverting to `0.94.1` version fixed the problem form me without doing anything else. Old implementation of table plugin not working on latest version of Flipper is an intended change?

**Comment by mweststrate** [comment]
Correct, we deprecated the API a few months ago and there didn't seem to be
any public users at that moment.

**Comment by dallasgutauckis** [comment]
We were using `createTablePlugin` internally (can't publish a plugin for external use that is internally use case specific). I'm looking at trying to upgrade to this new plugin architecture, but the docs are really confusing at this point. 

[This page](https://fbflipper.com/docs/extending/create-table-plugin/) (in Deprecated APIs) notes,

> The following mechanism isn't supported yet by the Sandy plugin architecture. Please remove `flipper-plugin` from the plugin dependencies if you want to use `createTablePlugin`.

While the [main tutorial](https://fbflipper.com/docs/tutorial/js-table) mentions the same API:

> `import {DataTableColumn, createTablePlugin} from 'flipper-plugin';`

I realize these are importing from different dependencies, but--and I'll admit I'm a newbie to React/JSX stuff--it seems like neither works as expected, whether I add or remove flipper-plugin from `peerDependencies` as mentioned in [Migrating a plugin to Sandy](https://fbflipper.com/docs/extending/sandy-migration)

----

1. I wanted to note that we internally were using this API
2. I am now wondering how to implement a table, especially given [none of the Table stuff is documented](https://fbflipper.com/docs/extending/flipper-plugin#datatable), assuming the current tutorial is just wrong and I'm not just misconfigured

**Comment by mweststrate** [comment]
Create table plugin has been updated and can be found here: https://fbflipper.com/docs/extending/flipper-plugin/#createtableplugin
