### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: 

### ISSUE THREAD

**Issue by afaucogney** [facebook/flipper#2768]
## 🐛 Bug Report

No way to start the development version (main branch)

## To Reproduce

I just upgrade to the latest versions (was still on master branch a couple of hours ago)
I get this error when 'yarn start'

App threw an error during load
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/aa/Documents/archi/git/flipper/desktop/node_modules/fix-path/index.js
require() of ES modules is not supported.
require() of /Users/aa/Documents/archi/git/flipper/desktop/node_modules/fix-path/index.js from /Users/aa/Documents/archi/git/flipper/desktop/static/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/aa/Documents/archi/git/flipper/desktop/node_modules/fix-path/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/aa/Documents/archi/git/flipper/desktop/node_modules/fix-path/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1169:13)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/afaucogney/Documents/archi/git/flipper/desktop/static/main.bundle.js:735:41
    at loadModuleImplementation (/Users/afaucogney/Documents/archi/git/flipper/desktop/static/main.bundle.js:285:7)
    at guardedLoadModule (/Users/afaucogney/Documents/archi/git/flipper/desktop/static/main.bundle.js:165:14)
    at metroRequire (/Users/afaucogney/Documents/archi/git/flipper/desktop/static/main.bundle.js:92:75)

## Environment

on macOs env

**Comment by tylercote** [comment]
+1 Having this issue as well.

**Comment by mweststrate** [comment]
Thanks for the report! Should be fixed soon.
