### ISSUE TITLE
Error: "dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by X"

### ISSUE THREAD

**Issue by justblender** [facebook/flipper#2862]
## 🐛 Bug Report
Debug builds crash on Android with the following error:
```
2021-09-13 21:00:18.289 11970-12007/com.redsteep.epicgrowth E/SoLoader: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/data/com.redsteep.epicgrowth/lib-main/libflipper.so"... result: 0
2021-09-13 21:00:18.290 11970-12008/com.redsteep.epicgrowth E/AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread
    Process: com.redsteep.epicgrowth, PID: 11970
    java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
2021-09-13 21:00:18.291 11970-12007/com.redsteep.epicgrowth E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.redsteep.epicgrowth, PID: 11970
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/data/com.redsteep.epicgrowth/lib-main/libflipper.so"... result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:918)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582)
        at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Backtrace" referenced by "/data/data/com.redsteep.epicgrowth/lib-main/libflipper.so"...
        at java.lang.Runtime.load0(Runtime.java:938)
        at java.lang.System.load(System.java:1631)
        at com.facebook.soloader.SoLoader$1.load(SoLoader.java:405)
        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
        at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:477)
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:860)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740) 
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654) 
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634) 
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:582) 
        at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19) 
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25) 
```

## To Reproduce
Build a React Native debug build through react-native-cli with Flipper enabled, run the application on Android 10 device.

## Environment
Android: 10.0 
React Native: 0.64.2

**Comment by justblender** [comment]
Just noticed that this might be a possible duplicate of #2765, but whatever.
