### ISSUE TITLE
Failed to compile Flipper Desktop for M1

### ISSUE THREAD

**Issue by lockieluke** [facebook/flipper#2898]
## 🐛 Bug Report

I tried to build Flipper Desktop for M1(arm64) but it failed.

```
/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61
		_this = _super.call(this, input.message || input) || this
                 ^
Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:317:21)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:327:19)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at isCompatibleEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:252:19)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:287:4)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
    at new Errlop (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/util.js:23:14)
    at isCompatibleEngines (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:183:19)
    at isCompatibleEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:250:10)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:287:4)
    at determineEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/sherlockluk/Desktop/flipper/desktop/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
```

## To Reproduce

Run `yarn build --mac`

## Environment

M1 MacBook Air - building Flipper Desktop

**Comment by passy** [comment]
From googling, this seems to be an issue with `app-builder-lib`. We're currently not on the latest version (I believe due to us also being behind on Electron). Could you check if upgrading `app-builder-lib` or `electron-builder` makes any difference?

**Comment by lockieluke** [comment]
```
Script termnated. Error: spawn zip ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn zip',
  path: 'zip',
  spawnargs: [ '-qyr9', '../Flipper-mac.zip', 'Flipper.app' ]
}
```

It just builds it as an .app bundle instead of a zip because of the error above

**Comment by lockieluke** [comment]
[Flipper for Apple Silicon](https://gofile.io/d/sicmC0)
[Direct Download Link](https://store1.gofile.io/download/51a77be3-7915-4b6d-839c-ac8b4fbc7e58/Flipper.zip) (Host: Gofile)

I built Flipper for arm64 without any modification except upgrading the libraries to make the build work.  When I run it, it says:

![image](https://user-images.githubusercontent.com/25424409/134505088-7dd216b1-fce8-44e7-a395-9fa557f6e6cc.png)

**Comment by mweststrate** [comment]
Fwiw I get that error sometimes in the console and it always goes away
after running yarn another time in desktop folder.

**Comment by colinbendell** [comment]
The root issue here is that the electron builder on an m1 puts the destination files in `dist/mac-arm64` and not the expected `dist/mac`

**Comment by gaweki** [comment]
is there update for this? still have this issue
