### ISSUE TITLE
Program type already present: com.facebook.soloader.Elf32_Dyn

### ISSUE THREAD

**Issue by juliafu1** [facebook/flipper#290]
Hi, 

I am trying to integrate Flipper into our Android app and it gave an error:

"Error: Program type already present: com.facebook.soloader.Elf32_Dyn
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:73)
	at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:306)
	at com.facebook.buck.android.DxStep.execute(DxStep.java:268)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:45)
	at com.facebook.buck.android.SmartDexingStep.lambda$null$1(SmartDexingStep.java:236)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)"

How shall I debug this?

**Comment by passy** [comment]
Have you tried excluding one SoLoader dependency in your build system?
