### ISSUE TITLE
"No Devices found" after upgrading to 0.113.0

### ISSUE THREAD

**Issue by hollysun09** [facebook/flipper#2947]
## 🐛 Bug Report
Failed to initialise ADB. Please disabled Android supportin settings, or configure a correct path Error: spawn /opt/android_sdk/platform-tools/adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)

    at onErrorNT (internal/child_process.js:469:16)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

## To Reproduce
Upgrade to 0.113.0 and plugin Android device to Mac.

## Environment
Pixel 4a
Android 11
Flipper 0.113.0

**Comment by hollysun09** [comment]
Solved by updating SDK location.
