### ISSUE TITLE
Question: I'm getting few errors in yarn step

### ISSUE THREAD

**Issue by PallaviTharigonda** [facebook/flipper#3142]
```
/home/ubuntu/flipper/desktop/node_modules/metro/src/IncrementalBundler.js:39
  _revisionsById = new Map();
                 ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/ubuntu/flipper/desktop/node_modules/metro/src/index.js:12:28)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

```

Can someone help me with this?

**Comment by mweststrate** [comment]
Please share your node and yarn version. Make sure to be at least on node 16

**Comment by mweststrate** [comment]
Closing for the lack of follow up info
