### ISSUE TITLE
Application crashes starting with 0.99.0 onwards when using fragment stack based navigation

### ISSUE THREAD

**Issue by mihaicristianpetrescu** [facebook/flipper#3172]
## 🐛 Bug Report

Android native application is crashing when navigation inside a fragment stack, namely when popping a fragment from the stack.

`java.lang.UnsupportedOperationException: removeView(View) is not supported in AdapterView
        at android.widget.AdapterView.removeView(AdapterView.java:543)
        at android.view.ViewOverlay$OverlayViewGroup.add(ViewOverlay.java:199)
        at android.view.ViewGroupOverlay.add(ViewGroupOverlay.java:72)
        at androidx.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:108)
        at androidx.transition.TransitionUtils.copyViewImage(TransitionUtils.java:64)
        at androidx.transition.Visibility.onDisappear(Visibility.java:401)
        at androidx.transition.Visibility.createAnimator(Visibility.java:257)
        at androidx.transition.Transition.createAnimators(Transition.java:747)
        at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:480)
        at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:480)
        at androidx.transition.Transition.playTransition(Transition.java:1821)
        at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:301)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3297)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8649)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:780)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

## To Reproduce
Use any Flipper library newer than 0.98.0 in order to make it crash.
Last known functioning Flipper library version is 0.98.0, from 0.99.0 onwards it crashes with the same stacktrace.

Use a Fragment stack based navigation and try to navigate back and forth. Potentially you'll also need to have a RecyclerView on one the first Fragment.

## Environment
Android OS 11/12
Min SDK 24
Compile + Target SDK 30

Flipper Desktop 0.125.0 - not relevant as its not opened
Mac OS 12.0.1
Android Studio Artic Fox 2020.3.1 Patch 4

**Comment by mweststrate** [comment]
I don't see anything Flipper related in your stack trace, could you clarify a bit more how this relates to Flipper, or reproduce the issue based on our example project? https://github.com/facebook/flipper/tree/main/android/sample

**Comment by mihaicristianpetrescu** [comment]
Yes, that's correct. It doesn't display any Flipper class lines, but if I use the older version, namely 0.98.0 and nothing newer, then it works just fine, without any code/library changes whatsoever, so that's how we concluded that the culprit is Flipper, because we just swapped different versions of Flipper until the app didn't crash anymore in that specific use case scenario.
Fragment navigation stack, pop all fragments from the stack.

**Comment by mweststrate** [comment]
Could you check if the problem is gone if you don't include the InspectorPlugin in Flipper? Basically disable the line in your code base that looks like this: https://github.com/facebook/flipper/blob/main/android/sample/src/debug/java/com/facebook/flipper/sample/FlipperInitializer.java#L44

**Comment by mihaicristianpetrescu** [comment]
Yes, of course. Testing now.

**Comment by mihaicristianpetrescu** [comment]
This is how we setup it currently:

`val client = AndroidFlipperClient.getInstance(context)
            val networkPlugin = NetworkFlipperPlugin()
            flipperInterceptor = FlipperOkhttpInterceptor(networkPlugin)
            client.addPlugin(InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()))
            client.addPlugin(DatabasesFlipperPlugin(context))
            client.addPlugin(SharedPreferencesFlipperPlugin(context))
            client.addPlugin(networkPlugin)
            client.start()`

I've disabled all the plugins and used the newer version 0.99.0/0.125.0 and it still crashes in the same scenario.

**Comment by mweststrate** [comment]
Ok, that sounds the problem lies somewhere else, is there another UI observer active? Is the NDK up to date, etc. Just checking, this even happens if the Flipper desktop isn't running at all, correct?

**Comment by mihaicristianpetrescu** [comment]
Another UI observer on any of the Fragments in the stack?
Yes, NDK is up-to-date and Flipper desktop app isn't running at all.

**Comment by mihaicristianpetrescu** [comment]
Seems like a combination of the following updates (not sure exactly if all are required to fix the crash):

build tools update to 32.0.0
kotlin version 1.6.10
kotlin compiler extensions 1.2.0-alpha01
room 2.4.1
navigation 2.3.5
lifecycleversion 2.4.0
okhttp 4.9.3
facebook 12.3.0

Fixed the problem.
Using Flipper 0.128.4 - latest as of now
