### ISSUE TITLE
Question: Hostname/IP does not match certificate's altnames:

### ISSUE THREAD

**Issue by huskyth** [facebook/flipper#3325]
desktop/node_modules/electron: Command failed. and node install.js
anyone can help me

**Comment by huskyth** [comment]
error /Users/tenghao/flipper/flipper/desktop/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/tenghao/flipper/flipper/desktop/node_modules/electron
Output:
RequestError: Hostname/IP does not match certificate's altnames: Host: github.com. is not in the cert's altnames: DNS:*.googlevideo.com, DNS:*.a1.googlevideo.com, DNS:*.bdn.dev, DNS:*.c.doc-0-0-sj.sj.googleusercontent.com, DNS:*.c.2mdn.net, DNS:*.dai.googlevideo.com, DNS:*.googlezip.net, DNS:*.gvt1.com, DNS:*.offline-maps.gvt1.com, DNS:*.snap.gvt1.com, DNS:*.gcpcdn.gvt1.com, DNS:xn--ngstr-lra8j.com, DNS:*.xn--ngstr-lra8j.com, DNS:i.ytimg.com, DNS:play-lh.googleusercontent.com
    at ClientRequest.<anonymous> (/Users/tenghao/flipper/flipper/desktop/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/Users/tenghao/flipper/flipper/desktop/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)

**Comment by huskyth** [comment]
error .../desktop/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: .../desktop/node_modules/electron
Output:
RequestError: Hostname/IP does not match certificate's altnames: Host: github.com. is not in the cert's altnames: DNS:*.googlevideo.com, DNS:*.a1.googlevideo.com, DNS:*.bdn.dev, DNS:*.c.doc-0-0-sj.sj.googleusercontent.com, DNS:*.c.2mdn.net, DNS:*.dai.googlevideo.com, DNS:*.googlezip.net, DNS:*.gvt1.com, DNS:*.offline-maps.gvt1.com, DNS:*.snap.gvt1.com, DNS:*.gcpcdn.gvt1.com, DNS:xn--ngstr-lra8j.com, DNS:*.xn--ngstr-lra8j.com, DNS:i.ytimg.com, DNS:play-lh.googleusercontent.com
    at ClientRequest.<anonymous> (.../desktop/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (.../desktop/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)

**Comment by lblasa** [comment]
Hi @huskyth, I'm not entirely sure what the problem is here other than this being a local issue. Could you please try to clean the workspace and try again?
