### ISSUE TITLE
Flipper crashes when running UI Tests - couldn't find DSO to load: libfbjni.so

### ISSUE THREAD

**Issue by woodii** [facebook/flipper#3357]
## 🐛 Bug Report
I have implemented Flipper with several plugins into my native android app. But unfortunately for some reason running UI tests does not work anymore when Flipper is enabled in the debug variant.

When running the app normally everything works fine and all SO Libs can be loaded. But when running an UI test the app itself crashes because SoLoader cannot find and load libfbjni.so. There are no issues with other SO libs from flipper regarding to the logs.

The apps process will then crash with the following exception.
`java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so`

<details>
<summary>Full Stacktrace</summary>

```
  D/SoLoader: libfbjni.so not found on /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
  D/SoLoader: libandroid.so not found on /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
  D/SoLoader: libandroid.so not found on /data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a
  D/SoLoader: libandroid.so found on /system/lib64
  D/SoLoader: libandroid.so loaded implicitly
  D/SoLoader: liblog.so not found on /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
  D/SoLoader: liblog.so not found on /data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a
  D/SoLoader: liblog.so found on /system/lib64
  D/SoLoader: liblog.so loaded implicitly
  D/SoLoader: libm.so not found on /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
  D/SoLoader: libm.so not found on /data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a
  D/SoLoader: libm.so found on /system/lib64
  D/SoLoader: libm.so loaded implicitly
  D/SoLoader: libdl.so not found on /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
  D/SoLoader: libdl.so not found on /data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a
  D/SoLoader: libdl.so found on /system/lib64
  D/SoLoader: libdl.so loaded implicitly
  D/SoLoader: libc.so not found on /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
  D/SoLoader: libc.so not found on /data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a
  D/ConnectionBase: Connected to androidx.test.orchestrator.OrchestratorService
  D/SoLoader: libc.so found on /system/lib64
  D/SoLoader: libc.so loaded implicitly
  W/SoLoader: libfbjni.so not found on DirectAPKSoSource: 4
      java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a/libfbjni.so" not found
          at java.lang.Runtime.load0(Runtime.java:929)
          at java.lang.System.load(System.java:1620)
          at com.facebook.soloader.SoLoader$1.load(SoLoader.java:529)
          at com.facebook.soloader.DirectApkSoSource.loadLibrary(DirectApkSoSource.java:77)
          at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1038)
          at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
          at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
          at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
          at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
          at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
          at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
          at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
          at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
  D/SoLoader: libfbjni.so not found on /system/lib64
  D/SoLoader: libfbjni.so not found on /vendor/lib64
  D/LeakCanary: LeakCanary is currently disabled: LeakCanary.Config.dumpHeap is set to false.
  E/SoLoader: couldn't find DSO to load: libfbjni.so
    	  SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64 flags = 0]
    	  SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a]
    	  SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	  SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	  Native lib dir: /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
       result: 0
  E/AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread
      Process: APPPACKAGENAME, PID: 18291
      java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
          at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
  E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
      Process: APPPACKAGENAME, PID: 18291
      java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so
    	  SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64 flags = 0]
    	  SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/~~NP0Yhz551EFUO_H4ouiOnw==/TESTPACKAGENAME-NKS-BK8gWrukWg0H_iY7dw==/base.apk!/lib/arm64-v8a]
    	  SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	  SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	  Native lib dir: /data/app/~~VveCAOV-RNpHrnMAZnfoiQ==/APPPACKAGENAME-ZAAR8SsdAJtiYPP3ybm2ug==/lib/arm64
       result: 0
          at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
          at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
          at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
          at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
          at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
          at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
          at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
          at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
          at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```
</details>

When looking into the apk the lib is included correctly.

## To Reproduce
Unfortunately i don't have any sample repository yet where this issue is reproducable.

## Environment

flipper 0.129.0
soloader 0.10.3
Tests are running on a Pixel6 A12 device.

**Comment by caraesten** [comment]
This bit me a number of times, and the solution is kind of annoying. Try seeing if the `.so` is included in the install directory for your app on the device; in my case, it was in the APK, but not there. The solution is to include `android:extractNativeLibs` in your manifest (see: https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs)

see this part, specifically:

> The default value is "true" if extractNativeLibs is not configured in AndroidManifest.xml. However, when building your app using Android Gradle plugin 3.6.0 or higher, this property is reset to "false" if it is NOT configured in AndroidManifest.xml and minSdkVersion >= 23. If minSdkVersion < 23 and extractNativeLibs is explicitly set to "false" in AndroidManifest.xml, you must add the following to your app's build.gradle file:

Once that's there, it should work.

**Comment by woodii** [comment]
@caraesten thanks! Your workaround solved the issue.
But I am still curious why this is only happening to one lib.

**Comment by passy** [comment]
Oh hi @caraesten! 👋 Thanks for helping out.

This seems to be some quirk in the Android Gradle Plugin. Let me know if there's something we can do on our end to make this easier, but otherwise I'll close this as there's a workaround.

**Comment by shensven** [comment]
#3395

**Comment by ducrohet** [comment]
I was just linked to this issue.

Please do note that putting `android:extractNativeLibs=true` in your `src/main/AndroidManifest.xml` will make AGP compress the `.so` files in your APK. In turn this forces the system to extract these files somewhere on device so that the system can read them.

Newer versions of Android support reading these files directly from the APK, if they are uncompressed. This leads to less on-device storage used by the app (one uncompressed copy vs one uncompressed + one compressed) even though the APK appears bigger.

AGP will automatically turn on the right mode based on your `minSdkVersion`. If you are in this situation and still need to disable this mode to run flipper, please make sure to only do it for debugging, and not release.
