### ISSUE TITLE
TypeError: Cannot read property 'shortcuts' of undefined

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/flipper#3358]
TypeError: Cannot read property 'shortcuts' of undefined

Flipper version: 0.129.0

Component stack:

    at SettingsSheet (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4218:1385)
    at TrackingScope (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1952:1646)
    at WithTrackingScope
    at Connect(WithTrackingScope) (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4135:3017)
    at ExtrasMenu (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4214:4691)
    at div
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:943:769
    at div
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:943:769
    at Layout.Bottom (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1973:2102)
    at div
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:943:769
    at LeftRail (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4214:2767)
    at TrackingScope (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1952:1646)
    at WithTrackingScope
    at div
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:943:769
    at div
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:943:769
    at Layout.Left (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1973:2155)
    at div
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:943:769
    at Layout.Bottom (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1973:2102)
    at div
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:943:769
    at SandyApp (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4213:1351)
    at TooltipProvider (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:3880:2110)
    at PersistGate (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4370:2634)
    at Provider (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4130:1014)
    at AppFrame (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4211:996)

Error stacktrace:
TypeError: Cannot read property 'shortcuts' of undefined
    at SettingsSheet.render (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:4218:5757)
    at qi (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:73994)
    at pi (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:73788)
    at Bl (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:110418)
    at bk (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:101446)
    at ak (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:101374)
    at Tj (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:101227)
    at Lj (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:98001)
    at file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:46741
    at _e.unstable_runWithPriority (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1018:3887)
    at gg (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:46516)
    at jg (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:46686)
    at ig (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:46619)
    at Hb (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:119009)
    at gd (file:///C:/Users/User/Downloads/Flipper-win/resources/app.asar/bundle.js:1007:25364)

**Comment by valery-lavrik** [comment]
> @valery-lavrik could you share some steps to reproduce?

1) download the windows version (I have win 10)
2) launch the application
3) open settings

I just tried again, downloaded a new build, the error remained...

![image](https://user-images.githubusercontent.com/8047999/153547592-d90ec707-8270-40fc-b78e-b265e647dfd4.png)

**Comment by aneemtalukder** [comment]
any updates on this issue?
