### ISSUE TITLE
[conn] Failed to find device 'unknown' while connection app ...

### ISSUE THREAD

**Issue by alfredarcifa** [facebook/flipper#3361]
Hi people,

I have an issue with Flipper :

[conn] Failed to find device 'unknown' while connection app 'AppName' Error: Timed out waiting for device unknown for client AppName
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4373:5711

with iOS Simulator 

Flipper version: 0.130.0

App Libriaries specs.:

"react-native": "0.64.1",
"react-native-flipper": "^0.88.0",
"react-redux": "^7.2.4",
"redux": "^4.1.0",
"redux-devtools-extension": "^2.13.9",
"redux-flipper": "^1.4.2",

thanks

**Comment by alfredarcifa** [comment]
Update:

Despite the above problem, I can see the Logs and the Hermes Debugger.
If instead, I want to use the React DevTools I have the following error:

_Uncaught Error: Cannot remove node "0" because no matching node was found in the Store.
Dismiss
The error was thrown at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5605:337615
    at kr.emit (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5605:281413)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5605:283045
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5605:688182
    at Array.forEach (<anonymous>)
    at A.oe.onmessage (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5605:688165)
    at A.t (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5596:3330)
    at A.emit (events.js:315:20)
    at oe.exports.L (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5560:14736)
    at oe.exports.emit (events.js:315:20)
    at oe.exports.dataMessage (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5560:21208)
    at oe.exports.getData (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5560:20405)
    at oe.exports.startLoop (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5560:17712)
    at oe.exports._write (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5560:17002)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)_

**Comment by Preshonyee** [comment]
I have the same issue too

**Comment by alfredarcifa** [comment]
> I have the same issue too

It's frustrating, I know!!!

Other specs:

macOS: Monterey
version 12.1


Please, help us!

**Comment by alfredarcifa** [comment]
Other info, when I try to open debug from Dev Menu in-app, in the console I see this:

info Opening flipper://null/Hermesdebuggerrn?device=React%20Native...

**Comment by cekkaewnumchai** [comment]
Apologize for the inconvenience. Flipper 0.130 is broken. Please update to version 0.131

**Comment by alfredarcifa** [comment]
> Edited: please download version 0.129 instead. There is a connection issue in version 0.130, and version 0.131 seems not to be published
> 
> Apologize for the inconvenience. Flipper 0.130 is broken. Please update to version 0.131

Hi @cekkaewnumchai ,

with 0.129 I see another error in console:

Ignoring malformed FLIPPER_BROWSER_PORT env variable:  "".     Example expected format: "1111".

[conn] Failed to find device 'unknown' while connection app 'Bennet' Error: Timed out waiting for device unknown for client Bennet

**Comment by alfredarcifa** [comment]
Hi @cekkaewnumchai ,

with https://github.com/facebook/flipper/releases/tag/v0.131.1 I haven't any connection problem.

Thanks.

**Comment by jb9229** [comment]
I have the same issue too

v0.129, v0.131.1

**Comment by aigoncharov** [comment]
@jb9229 if you have connection issues with 0.131.1, could you create a new issue with steps to reproduce?

**Comment by kbirgoren** [comment]
I have the same issue.

`[conn] Failed to find device '7F017CFA-5EAB-4285-8AED-77E14A717BCE' while connection app 'MyApp' Error: Timed out waiting for device 7F017CFA-5EAB-4285-8AED-77E14A717BCE for client MyApp
    at file:///Applications/[Flipper.app/Contents/Resources/app.asar/bundle.js:4209:5711](http://flipper.app/Contents/Resources/app.asar/bundle.js:4209:5711)`
    
   It just works fine with Android emulator devices but not with iOS simulators.
