### ISSUE TITLE
FATAL EXCEPTION: FlipperConnectionThread

### ISSUE THREAD

**Issue by shensven** [facebook/flipper#3395]
## 🐛 Bug Report

```
FATAL EXCEPTION: FlipperConnectionThread

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libevent_core-2.1.so" not found

FATAL EXCEPTION: FlipperConnectionThread
Process: com.readhubn, PID: 3370
java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)

FATAL EXCEPTION: FlipperEventBaseThread
Process: com.readhubn, PID: 3370
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: library "libevent_core-2.1.so" not found result: 0
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
	at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libevent_core-2.1.so" not found
	at java.lang.Runtime.load0(Runtime.java:938)
	at java.lang.System.load(System.java:1631)
	at com.facebook.soloader.SoLoader$1.load(SoLoader.java:529)
	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:110)
	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
	at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:91)
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1038)
	... 6 more
```

## To Reproduce

update flipper from `v0.131.1` to `v0.132.0`, android app crash after command `yarn android`

## Environment

```
System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 43.30 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /var/folders/yx/96bg23w10x5c7mstcj4rdwxw0000gn/T/yarn--1643901794190-0.5066931032750883/node
    Yarn: 1.22.15 - /var/folders/yx/96bg23w10x5c7mstcj4rdwxw0000gn/T/yarn--1643901794190-0.5066931032750883/yarn
    npm: 8.4.0 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
```gradle
// android/build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven { url 'https://www.jitpack.io' }
    }
}

```
```properties
# android/gradle.properties
# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Version of flipper SDK to use with React Native
FLIPPER_VERSION=0.132.0
```

**Comment by paour** [comment]
The APK when build with `0.132.0` is indeed missing `libevent_core-2.1.so`. A downgrade to `0.131.1` fixes this.

**Comment by shensven** [comment]
android version still crash at v0.133.0
https://github.com/facebook/flipper/releases/tag/v0.133.0

**Comment by passy** [comment]
Not sure what could have changed that. We had a few gradle plugin upgrades. I'll investigate but probably won't have time before next week.

**Comment by passy** [comment]
This is quite mysterious indeed. I can see that the file just disappeared from `flipper-0.132.0.aar` while it was still present in `flipper-0.131.0.aar`. Furthermore, building it locally both in debug and release mode using `./gradlew :android:assembleDebug` (or `Release`), the `libevent_core-2.1.so` is only present for x86 and armeabi-v7a but not for x86_64 and arm64-v8a. This all looks a little fishy but I don't have any good ideas for why that might happen.

**Comment by passy** [comment]
Using a rather dumb bisect script to narrow this down:

```
#!/usr/bin/bash

git clean -fdx
./gradlew :android:assembleDebug --no-daemon
NUM=$(unzip -l android/build/outputs/aar/android-debug.aar | rg _core | wc -l)

if (( $NUM >= 4 )); then
        echo "Found enough: $NUM"
        exit 0
else
        echo "Too few: $NUM"
        exit 1
fi
```

**Comment by lblasa** [comment]
Need to look this one into more detail, but the problem started with the upgrade of the gradle.
The issue happens with 'com.android.tools.build:gradle:7.1.1' but not for 'com.android.tools.build:gradle:7.0.2'.

As a temporary workaround, downgrading to 7.0.2 should fix the issue.

**Comment by passy** [comment]
That came back from the bisect, too. 9f31be1128342175234b07436cf462fe58e76845 broke the build. Not sure what exactly it is but I'll revert this back tomorrow.

**Comment by passy** [comment]
That's ecd726984854aa6d39a3d6490b212329a5fa6b43 in git.
