### ISSUE TITLE
Error: Uncaught Error: Unsupported Bridge operation "0"

### ISSUE THREAD

**Issue by kovkev** [facebook/flipper#3399]
## 🐛 Bug Report
I try to use Flipper on my project for the first time. I am met with an error `Uncaught Error: Unsupported Bridge operation "0"`

## To Reproduce
React-native init a project
Setup hermes=true
Run the project on ios Simulator
Open Flipper
Access the React Native tab
See the error

## Environment
Flipper 0.132.0
React-Native 0.67

In red:
```
Uncaught Error: Unsupported Bridge operation "0"
Dismiss
The error was thrown at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5442:339974
    at kr.emit (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5442:281413)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5442:283045
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5442:688182
    at Array.forEach (<anonymous>)
    at A.oe.onmessage (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5442:688165)
    at A.t (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5433:3330)
    at A.emit (events.js:315:20)
    at oe.exports.L (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5397:14736)
    at oe.exports.emit (events.js:315:20)
    at oe.exports.dataMessage (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5397:21208)
    at oe.exports.getData (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5397:20405)
    at oe.exports.startLoop (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5397:17712)
    at oe.exports._write (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:5397:17002)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
```

**Comment by kovkev** [comment]
The logs are showing logs from the react-native app code

**Comment by kovkev** [comment]
Also, the Hermes Debugger (RN) tab has all its tabs empty of any activity

**Comment by mweststrate** [comment]
To clarify, is this about the Hermes, React DevTools or other plugin?

**Comment by AdityaVMT** [comment]
its came from react dev tools

**Comment by AmorimRob** [comment]
same error here

**Comment by swelly-ian** [comment]
Same here, latest versions of all packages.

**Comment by marcshilling** [comment]
What got things working for me:

In package.json
```
  "resolutions": {
    "react-devtools-core": "4.23.0"
  },
```

I do not have `react-devtools` installed globally.

**Comment by FadiAboMsalam** [comment]
same issue

**Comment by catericy** [comment]
same issue
