### ISSUE TITLE
Failed to exchange certificate with iPhone Simulator in 0.132.0

### ISSUE THREAD

**Issue by johanhubens** [facebook/flipper#3421]
## 🐛 Bug Report
After updating to Flipper v0.132.0, it cannot connect to (React Native) apps running on iPhone Simulator. The selection dropdown in Flipper app shows the app under "React Native", "Currently connecting", but it never connects. The Flipper logs show the following error:

```
[conn] Failed to exchange certificate with <AppName> on iPhone Simulator 
Error: No iOS devices found
    at iOSCertificateProvider.getTargetDeviceId (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:401:1012)

    at async iOSCertificateProvider.processCertificateSigningRequest (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:186:708)
```

Additional notes:
- Updating only the Flipper pod(s) to v0.132.0 using `use_flipper!({ 'Flipper' => '0.132.0' })` in combination with the Flipper app v0.131.1 still seems to work.
- Updating both the Flipper pods and the Flipper app from v0.131.1 to v0.132.0 seems to work for existing apps installed on the simulator, after rebuilding with the new version. It stops working after deleting the app and reinstalling it.
- Workaround for now is to keep both the Flipper pods and desktop app on v0.131.1 where everything works fine.

## To Reproduce
In a React Native CLI project:
- Update Flipper pod(s) from v0.131.1 to v0.132.0 using `use_flipper!({ 'Flipper' => '0.132.0' })` in `ios/Podfile`.
- Run `pod install --repo-update` in the `ios` directory.
- Remove the app from iPhone Simulator, if it was already installed, or start with a clean iPhone Simulator.
- Build and run the app on iPhone Simulator.

- Update Flipper app to v0.132.0 and run it.

## Environment
- React Native CLI project with Flipper v0.132.0
- iPhone 12 Simulator / iOS 15.2
- Flipper Desktop version: 0.132.0
- Apple M1 / MacOS 12.1

**Comment by essana3** [comment]
#3396

**Comment by andreygamb** [comment]
Hi! any solutions?

**Comment by uguraktas** [comment]
Have same issue.

**Comment by bodrius** [comment]
+++
