### ISSUE TITLE
RecurringError: Client setup error: Premature end of stream, needed 4 more bytes

### ISSUE THREAD

**Issue by jknoxville** [facebook/flipper#344]
I got this error:
connections.js:315 RecurringError: Client setup error: Premature end of stream, needed 4 more bytes
    at reducer (http://localhost:3000/src/init.bundle:51768:25)
    at http://localhost:3000/src/init.bundle:101421:22
    at combination (http://localhost:3000/src/init.bundle:3895:31)
    at computeNextEntry (<anonymous>:1:35747)
    at recomputeStates (<anonymous>:1:36047)
    at <anonymous>:1:39722
    at Object.dispatch (http://localhost:3000/src/init.bundle:3713:24)
    at Object.dispatch (<anonymous>:1:40228)
    at Server.server.addListener.payload (http://localhost:3000/src/init.bundle:102718:13)
    at Server.emit (events.js:182:13)
    at certificateProvider.processCertificateSigningRequest.then.catch.e (http://localhost:3000/src/init.bundle:60189:24)
    at process._tickCallback (internal/process/next_tick.js:68:7) "Android:INFINIX-X551 - 5.1 - API 22:Jumia Candidate"

Any Idea?

_Originally posted by @simaofelgueirasJM in https://github.com/facebook/flipper/issues/342#issuecomment-448309615_

**Comment by passy** [comment]
I'm cleaning up some old issues and this one hasn't seen updates in a long time. Please let me know if this is still a problem and we can reopen it. Thanks!
