### ISSUE TITLE
Soloader crash during instrumented test

### ISSUE THREAD

**Issue by vvasilev92** [facebook/flipper#3499]
## 🐛 Bug Report

For some reason SoLoader decides to look for libfbjni in the .test path during instrumented tests. I am not sure how it makes that decision, since package name still reports without .test.
System.loadLibrary("fbjni") succeeds. Is there some special way to do this for instrumented tests, I am unsure how to find out the app is running an instrumented test and disable loading of flipper, since both variants are debug. I need to look into the code for DirectApkSoSource but is this intended behavior?

```
E/MonitoringInstr: Exception encountered by: Thread[FlipperEventBaseThread,5,main]. Dumping thread state to outputs and pining for the fjords.
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so
    	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com.*******.*****-GbO9iOO3uN07CjCW8yS_pQ==/lib/x86 flags = 0]
    	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = /data/app/com.*******.*****.test-Ki-oH9jGGxckEGeo3ucGBw==/base.apk!/lib/x86]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
    	Native lib dir: /data/app/com.*******.*****-GbO9iOO3uN07CjCW8yS_pQ==/lib/x86
     result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
        at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
E/MonitoringInstr: Exception encountered by: Thread[FlipperConnectionThread,5,main]. Dumping thread state to outputs and pining for the fjords.
```

**Comment by passy** [comment]
Sorry, I don't think we'll be able to provide much support here as this is SoLoader-specific and we don't run tests like that ourselves but I'll leave it open in case someone else knows how to work around this.

**Comment by CiaraSouthgateFT** [comment]
I'm also having this issue and would be very grateful for a workaround.

**Comment by CiaraSouthgateFT** [comment]
I have found a (very hacky) workaround to detect whether you're running instrumented tests: https://stackoverflow.com/questions/21367646/how-to-determine-if-android-application-is-started-with-junit-testing-instrument?noredirect=1&lq=1

**Comment by tinder-cesardiez** [comment]
Any updates on this? We are running into the same issue at Tinder.

**Comment by tinder-cesardiez** [comment]
Issue seems to be gone for us after updating the SoLoader dependency to 10.0.4:
https://github.com/facebook/SoLoader/releases/tag/v0.10.4
