### ISSUE TITLE
A crash was detected in the Flipper chrome

### ISSUE THREAD

**Issue by asim019** [facebook/flipper#3501]
## 🐛 Bug Report

TypeError: Cannot read property 'shortcuts' of undefined

Flipper version: 0.137.0

Component stack:

    at SettingsSheet (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4069:1385)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1804:1646)
    at WithTrackingScope
    at Connect(WithTrackingScope) (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3985:3017)
    at ExtrasMenu (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:4741)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:793:769
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:793:769
    at Layout.Bottom (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1825:2102)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:793:769
    at LeftRail (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:2817)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1804:1646)
    at WithTrackingScope
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:793:769
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:793:769
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1825:2155)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:793:769
    at Layout.Bottom (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1825:2102)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:793:769
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4064:1351)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3730:2110)
    at PersistGate (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4221:2634)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3980:1014)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4062:996)

Error stacktrace:
TypeError: Cannot read property 'shortcuts' of undefined
    at SettingsSheet.render (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4069:5769)
    at qi (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:73994)
    at pi (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:73788)
    at Bl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:110418)
    at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:101446)
    at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:101374)
    at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:101227)
    at Lj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:98001)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46741
    at _e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:869:3887)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46516)
    at jg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46686)
    at ig (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46619)
    at Hb (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:119009)
    at gd (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:25364)

## To Reproduce
click to open settings

## Environment
mac Monterey

**Comment by passy** [comment]
Just tried this on Monterey with the public build but can't reproduce it unfortunately. It looks like you may have upgraded from an old version and something in the settings is incompatible now. Could you please removing/renaming your `$HOME/.flipper` folder?
