### ISSUE TITLE
TypeError: Cannot read property 'shortcuts' of undefined

### ISSUE THREAD

**Issue by aneemtalukder** [facebook/flipper#3546]
Seeing this crash when I try to open Settings. I have also deleted $HOME/.flipper with no luck

TypeError: Cannot read property 'shortcuts' of undefined

Flipper version: 0.139.0

Component stack:

    at SettingsSheet (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4070:1385)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1804:1646)
    at WithTrackingScope
    at Connect(WithTrackingScope) (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3986:3017)
    at ExtrasMenu (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4066:4741)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:792:1525
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:792:1525
    at Layout.Bottom (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1825:2102)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:792:1525
    at LeftRail (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4066:2817)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1804:1646)
    at WithTrackingScope
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:792:1525
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:792:1525
    at Layout.Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1825:2155)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:792:1525
    at Layout.Bottom (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1825:2102)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:792:1525
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4065:1351)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3731:2110)
    at PersistGate (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4222:2634)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3981:1014)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4063:996)

Error stacktrace:
TypeError: Cannot read property 'shortcuts' of undefined
    at SettingsSheet.render (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4070:5848)
    at qi (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:73994)
    at pi (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:73788)
    at Bl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:110418)
    at bk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:101446)
    at ak (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:101374)
    at Tj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:101227)
    at Lj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:98001)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46741
    at _e.unstable_runWithPriority (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:869:3887)
    at gg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46516)
    at jg (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46686)
    at ig (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:46619)
    at Hb (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:119009)
    at gd (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:858:25364)

**Comment by buptfarmer** [comment]
I encountered similar issue.  in Flipper version: 0.144.0

**Comment by buptfarmer** [comment]
Hi, I fixed the crash with the code below.
Actually wrap the tooglebutton by condition check whether reactNative exist.  
It seems missing update the reactNative settings.  

// SettingsSheet.tsx

```

        {reactNative && reactNative.shortcuts && (
          <ToggledSection
            label="React Native keyboard shortcuts"
            toggled={reactNative.shortcuts.enabled}
            onChange={(enabled) => {
              this.setState((prevState) => ({
                updatedSettings: {
                  ...prevState.updatedSettings,
                  reactNative: {
                    ...prevState.updatedSettings.reactNative,
                    shortcuts: {
                      ...prevState.updatedSettings.reactNative.shortcuts,
                      enabled,
                    },
                  },
                },
              }));
            }}>
            <KeyboardShortcutInput
              label="Reload application"
              value={reactNative.shortcuts.reload}
              onChange={(reload) => {
                this.setState((prevState) => ({
                  updatedSettings: {
                    ...prevState.updatedSettings,
                    reactNative: {
                      ...prevState.updatedSettings.reactNative,
                      shortcuts: {
                        ...prevState.updatedSettings.reactNative.shortcuts,
                        reload,
                      },
                    },
                  },
                }));
              }}
            />
            <KeyboardShortcutInput
              label="Open developer menu"
              value={reactNative.shortcuts.openDevMenu}
              onChange={(openDevMenu) => {
                this.setState((prevState) => ({
                  updatedSettings: {
                    ...prevState.updatedSettings,
                    reactNative: {
                      ...prevState.updatedSettings.reactNative,
                      shortcuts: {
                        ...prevState.updatedSettings.reactNative.shortcuts,
                        openDevMenu,
                      },
                    },
                  },
                }));
              }}
            />
          </ToggledSection>
        )}
```

**Comment by georgezhang** [comment]
Same issue on Mac ventura 13.2.1
==================
TypeError: Cannot read properties of undefined (reading 'shortcuts')

Flipper version: 0.188.0

Component stack:

    at SettingsSheet (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4351:2367)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1380:2065)
    at WithTrackingScope
    at ConnectFunction (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1317:5510)
    at ExtrasMenu (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4344:5993)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1281:2107
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1281:2107
    at Bottom (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1397:2779)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1281:2107
    at LeftRail (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4344:3651)
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1380:2065)
    at WithTrackingScope
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1281:2107
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1281:2107
    at Left (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1397:2857)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1281:2107
    at Bottom (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1397:2779)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1281:2107
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1372:1941)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4109:2814)
    at PersistGate (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4645:3375)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1309:1379)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1258:1777)

Error stacktrace:
TypeError: Cannot read properties of undefined (reading 'shortcuts')
    at SettingsSheet.render (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4351:8141)
    at Hj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:92761)
    at Gj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:92554)
    at ll (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:124231)
    at kl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:118004)
    at jl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:117935)
    at Zk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:117794)
    at Vk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:114849)
    at og (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:49221)
    at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:115155)
    at Nb (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:17011)
    at ld (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:41452)
    at jd (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:25472)
    at id (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1358:25260)

**Comment by sairus2k** [comment]
Workaround for the error: 

1. Open devtools in flipper (View -> Toggle Developer Tools)
2. Past and execute this code in console:
```js
window.flipperStore.dispatch({
  type: "UPDATE_SETTINGS",
  payload: {
    ...window.flipperStore.getState().settingsState,
    reactNative: { shortcuts: {} },
  },
});
```

**Comment by IgorMing** [comment]
same issue here. Version 0.239.0 (50.0.0)

react-native: "0.72.6"
react-native-flipper: "^0.212.0"
