### ISSUE TITLE
dlopen failed libflipper.so...

### ISSUE THREAD

**Issue by Neo-Turak** [facebook/flipper#3572]
## 🐛 Bug Report
 FlipperConnectionThread

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "BN_set_flags" referenced by "/data/app/com.easyhome.serve--F4N2u-7bnXGAcmAfJb1TQ==/lib/arm64/libflipper.so"...

FATAL EXCEPTION: FlipperConnectionThread
Process: com.easyhome.serve, PID: 13624
java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)

FATAL EXCEPTION: FlipperEventBaseThread
Process: com.easyhome.serve, PID: 13624
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "BN_set_flags" referenced by "/data/app/com.easyhome.serve--F4N2u-7bnXGAcmAfJb1TQ==/lib/arm64/libflipper.so"... result: 0
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
	at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "BN_set_flags" referenced by "/data/app/com.easyhome.serve--F4N2u-7bnXGAcmAfJb1TQ==/lib/arm64/libflipper.so"...
	at java.lang.Runtime.load0(Runtime.java:928)
	at java.lang.System.load(System.java:1633)
	at com.facebook.soloader.SoLoader$1.load(SoLoader.java:529)
	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:110)
	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
	at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:91)
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1038)
	... 6 more

## To Reproduce
 just need to open.

## Environment

Android Version 0.140.0
Desktop 0.140.0
Ubuntu 22.04

**Comment by ahmetberkinc** [comment]
I faced the same problem, did you find a solution?

**Comment by ruben4mobile** [comment]
Same issue on old android 5 device from huawei : Huawei GRA-L09

**Comment by sinergy** [comment]
Same issue with flipper version either `0.143.0` or `0.137` on emulator with API level 21.
We use flipper version `0.82.0` on same emulator without this issue before.

**Comment by pedromalta** [comment]
Same issue here

**Comment by pauledwardtang** [comment]
Also seeing this on Android 5.0 emulator using Flipper version `0.143.0`

**Comment by jukov** [comment]
Wrap in version check can fix crash:

```
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP_MR1) {
            FlipperUtil.init(this)
        }
```

But I think it should be included in lib and seems like Flipper is not available on earlier Android versions.

**Comment by kevinguitar** [comment]
Same issue here, any updates? 🙏 
Happened only on the versions before Android 6

**Comment by xerdnew** [comment]
Did you ever find a solution for this? I am having the same problem.

When using older version of Flipper it starts working again :(

```
# Version of flipper SDK to use with React Native
#FLIPPER_VERSION=0.182.0
FLIPPER_VERSION=0.125.0
```

**Comment by krmao** [comment]
> Did you ever find a solution for this? I am having the same problem.
> 
> When using older version of Flipper it starts working again :(
> 
> ```
> # Version of flipper SDK to use with React Native
> #FLIPPER_VERSION=0.182.0
> FLIPPER_VERSION=0.125.0
> ```

it works like a charm !!! @xerdnew

**Comment by jpetersen23** [comment]
For some future person trying to get react native > 0.73 working on lollipop. The code to prevent this crash now
```
 if (Build.VERSION.SDK_INT > Build.VERSION_CODES.LOLLIPOP_MR1) {
       ReactNativeFlipper.initializeFlipper(this, reactNativeHost.reactInstanceManager)
 }
```

The way flipper is integrated into the latest version of react native doesn't allow for the previous version downgrading, so the previous downgrade that used to work to 0.125.0 doesnt any longer (or I couldnt spot how to do it).

Adding a link in case someones tries to track back this crash fix again:
https://github.com/reactwg/react-native-releases/discussions/54
https://github.com/reactwg/react-native-releases/discussions/64

The crash will look like 

> E/AndroidRuntime( 9889): FATAL EXCEPTION: FlipperEventBaseThread
E/AndroidRuntime( 9889): Process: com.broken.app, PID: 9889
E/AndroidRuntime( 9889): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: cannot locate symbol "BN_set_flags" referenced by "/data/app/com.broken.app-1/lib/arm64/libflipper.so"... result: 0
E/AndroidRuntime( 9889): 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1228)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:1044)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:956)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:903)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:869)
E/AndroidRuntime( 9889): 	at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
E/AndroidRuntime( 9889): 	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
E/AndroidRuntime( 9889): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "BN_set_flags" referenced by "/data/app/com.broken.app-1/lib/arm64/libflipper.so"...
E/AndroidRuntime( 9889): 	at java.lang.Runtime.load(Runtime.java:331)
E/AndroidRuntime( 9889): 	at java.lang.System.load(System.java:982)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.SoLoader$1.load(SoLoader.java:650)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:115)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:68)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:92)
E/AndroidRuntime( 9889): 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1168)
E/AndroidRuntime( 9889): 	... 6 more
