### ISSUE TITLE
 Uncaught Error: Cannot remove node "0" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by Pra3t0r5** [facebook/flipper#3649]
## 🐛 Bug Report
Uncaught Error: Cannot remove node "0" because no matching node was found in the Store.
```
Dismiss
The error was thrown at file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:5480:782627
    at Bridge.emit (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:5480:54856)
    at file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:5480:52683
    at file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:5478:4705
    at file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:1784:230
    at gl (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:835:115268)
    at file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:1784:219
    at EventEmitter.subscriptionCb (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:4134:344)
    at EventEmitter.emit (events.js:315:20)
    at FlipperServerImpl.emit (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:6:8969)
    at ServerAddOnModuleToDesktopConnection.onMessage (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:734:779)
    at ServerAddOnModuleToDesktopConnection.emit (events.js:315:20)
    at ServerAddOnModuleToDesktopConnection.send (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:735:679)
    at WebSocket.<anonymous> (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:743:1453)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (file:///home/fernando/Programs/Flipper/Flipper-linux/resources/app.asar/bundle.js:3667:13511)
```

## To Reproduce
`yarn workspace mobile start` (to start metro)
`yarn workspace mobile android` (to build my android app)

## Environment
- env
```bash 
~/Projects/react/myapp$ java -version
openjdk version "1.8.0_312"
~/Projects/react/myapp$ node -v
v14.17.1
```
- myapp/packages/mobile/package.json
```json
{
  "name": "mobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "android:clean": "cd android; ./gradlew clean",
    "adb:restart": "adb shell pm clear com.myapp.app; adb shell am start -n com.myapp.app/com.myapp.app.MainActivity; adb reverse tcp:8081 tcp:8081",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "pod": "cd ios && pod"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "@invertase/react-native-apple-authentication": "^2.1.2",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/cli": "^4.14.0",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "^3.2.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/google-signin": "^5.0.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-firebase/app": "^10.8.1",
    "@react-native-firebase/auth": "^10.8.1",
    "@react-native-firebase/firestore": "^10.8.1",
    "@react-native-firebase/storage": "^10.8.1",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/drawer": "^5.3.4",
    "@react-navigation/material-bottom-tabs": "^5.1.6",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.7",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "add": "^2.0.6",
    "axios": "^0.20.0",
    "axios-cache-adapter": "^2.7.3",
    "color": "^3.1.2",
    "date-fns": "^2.28.0",
    "expo": "~36.0.0",
    "get-yarn-workspaces": "1.0.2",
    "i18n-js": "^3.8.0",
    "query-string": "^7.0.0",
    "react": "16.13.1",
    "react-art": "^16.13.1",
    "react-devtools": "^4.24.4",
    "react-dom": "^16.13.1",
    "react-native": "0.63.2",
    "react-native-branch": "^5.0.0",
    "react-native-create-thumbnail": "^1.4.1",
    "react-native-date-picker": "^3.2.10",
    "react-native-exception-handler": "^2.10.10",
    "react-native-fast-image": "^8.3.4",
    "react-native-ffmpeg": "^0.5.1",
    "react-native-fs": "^2.16.6",
    "react-native-gallery": "^0.0.17",
    "react-native-gallery-swiper": "^1.26.4",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-get-random-values": "^1.6.0",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-google-places-autocomplete": "^2.1.3",
    "react-native-image-crop-picker": "^0.33.2",
    "react-native-image-picker": "^3.1.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-localize": "^2.1.1",
    "react-native-macos": "^0.63.15",
    "react-native-mentions": "^1.1.4",
    "react-native-mime-types": "^2.3.0",
    "react-native-modal": "^11.5.6",
    "react-native-modal-datetime-picker": "^9.2.0",
    "react-native-paper": "^3.6.0",
    "react-native-parsed-text": "^0.0.22",
    "react-native-permissions": "^3.0.0",
    "react-native-push-notification": "^7.2.3",
    "react-native-reanimated": "~1.4.0",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "2.4.0",
    "react-native-segmented-text-input": "^0.0.1-alpha.9",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "2.11.0",
    "react-native-thumbnail-grid": "^0.3.0",
    "react-native-toast-message": "^1.4.9",
    "react-native-twitter-textview": "^1.0.6",
    "react-native-url-preview": "^1.1.9",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.1.1",
    "react-native-web": "~0.11.7",
    "react-scripts": "3.4.3",
    "react-timeago": "^5.2.0",
    "redux-persist": "^6.0.0",
    "rn-test-exception-handler": "^1.3.2",
    "twitter-text": "^3.1.0",
    "use-debounce": "^6.0.1"
  },
  "resolutions": {
    "react-navigation-tabs/react-native-tab-view": "2.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.3.0",
    "eslint": "^7.6.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "jest": "^26.3.0",
    "metro-react-native-babel-preset": "^0.62.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

## More 
Running:
`adb shell am start -n com.myapp.app/com.facebook.flipper.android.diagnostics.FlipperDiagnosticActivity`
I get:
![msg460729305-25938](https://user-images.githubusercontent.com/38087682/164562271-b5faf3c9-5ee9-4887-9829-a38826a3a9d3.jpg)

**Comment by yaseen256** [comment]
I am facing same issue.
my OS is Ubuntu 20.04.4 LTS
I can not see React devtools in Flipper. did you found any workaround? @Pra3t0r5

**Comment by 2sem** [comment]
![스크린샷 2022-06-03 오후 4 11 23](https://user-images.githubusercontent.com/16129260/171805635-f6f096d9-8a7c-487e-b4aa-de0cfc1c9520.png)
What the...?

Redux Debugger works well.

**Comment by zamplyy** [comment]
@2sem Did you find a fix?

**Comment by thaiscristine** [comment]
Same issue here

**Comment by 2sem** [comment]
I guess this is react-devtools issue.
I got same error from react-devtools standalone

**Comment by kofkgoing** [comment]
I found a solution.
<img width="203" alt="스크린샷 2022-10-09 오후 12 21 26" src="https://user-images.githubusercontent.com/85471652/194736258-eedc9750-8b30-4d60-b912-81b3c3ba022f.png">

"react-devtools-core": "4.24.3",


  "resolutions": {
    "react-devtools-core": "4.24.3"
  },

<img width="361" alt="스크린샷 2022-10-09 오후 12 22 04" src="https://user-images.githubusercontent.com/85471652/194736271-dcec9c64-b42f-468b-ad31-1cfe783a8559.png">
