### ISSUE TITLE
Mac Flipper Error

### ISSUE THREAD

**Issue by jayynn** [facebook/flipper#3738]

**Comment by jayynn** [comment]
Failed to start FlipperServer Error: Using configuration from /usr/local/ssl/openssl.cnf
Generating RSA private key, 2048 bit long modulus

...+++

........................................................................................................+++

e is 65537 (0x010001)


    at ChildProcess.<anonymous> (file:///Applications/[Flipper.app/Contents/Resources/app.asar/bundle.js:3246:1874](http://flipper.app/Contents/Resources/app.asar/bundle.js:3246:1874))

    at ChildProcess.emit (events.js:315:20)

    at maybeClose (internal/child_process.js:1021:16)

    at Socket.<anonymous> (internal/child_process.js:443:11)

    at Socket.emit (events.js:315:20)

    at Pipe.<anonymous> (net.js:674:12)

**Comment by bleszerd** [comment]
Same here. 

Windows 11 Pro - 10.0.22000 (22000)
Flipper stable channel 0.156.0

```txt
Failed to start flipper-server
Error: Loading 'screen' into random state - done Generating RSA private key, 2048 bit long modulus ........................................................................................+++ ......+++ e is 65537 (0x10001)
```

[flipper.log](https://github.com/facebook/flipper/files/9219911/flipper.log)

**Comment by kyimoemin** [comment]
same here, any solutions?

**Comment by jgudo** [comment]
Any solution to this?

**Comment by jgudo** [comment]
For windows: 
Apparently, I just needed to re-install OpenSSL using the MSI installer as instructed on the Flipper setup website using this link [https://slproweb.com/products/Win32OpenSSL.html](download-openssl)  in drive C:\  
and make sure to set the user  environment variable in PATH of the openssl ```bin``` directory.  
Moreover, I had to set environment variable RANDFILE to path where the ```random state``` can be written using the following command:
```set RANDFILE=C:\Users\<MyUser>\.rnd```

Then after closing and re-opening flipper app, boom it finally worked.

**Comment by orhangazi** [comment]
> For windows: Apparently, I just needed to re-install OpenSSL using the MSI installer as instructed on the Flipper setup website using this link [https://slproweb.com/products/Win32OpenSSL.html](download-openssl) in drive C:\ and make sure to set the user environment variable in PATH of the openssl `bin` directory. Moreover, I had to set environment variable RANDFILE to path where the `random state` can be written using the following command: `set RANDFILE=C:\Users\<MyUser>\.rnd`
> 
> Then after closing and re-opening flipper app, boom it finally worked.

This is not work for me.

**Comment by orhangazi** [comment]
> Same here.
> 
> Windows 11 Pro - 10.0.22000 (22000) Flipper stable channel 0.156.0
> 
> ```
> Failed to start flipper-server
> Error: Loading 'screen' into random state - done Generating RSA private key, 2048 bit long modulus ........................................................................................+++ ......+++ e is 65537 (0x10001)
> ```
> 
> [flipper.log](https://github.com/facebook/flipper/files/9219911/flipper.log)

Any solution to this?

**Comment by kyimoemin** [comment]
as @jgudo said, reinstalling the OpenSSL works for me. I don't even need to set `RANDFILE`
