### ISSUE TITLE
Crash when trying to remove a mock network call

### ISSUE THREAD

**Issue by davis-isaac** [facebook/flipper#3799]
## 🐛 Bug Report
Attempting to remove a mock network call causes a crash

> PLUGIN "NETWORK" ENCOUNTERED AN ERROR DURING RENDER
> TypeError: Cannot read property 'requestUrl' of undefined
>     at file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:5706:1452
>     at Array.reduce (<anonymous>)
>     at _duplicateIds (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:5706:1395)
>     at file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:5706:2395
>     at Object.Ji [as useMemo] (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:70803)
>     at _e.useMemo (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:61:6829)
>     at ManageMockResponsePanel (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:5706:2389)
>     at ci (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:66423)
>     at Cj (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:89605)
>     at ll (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:124147)
>     at kl (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:118004)
>     at jl (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:117935)
>     at Zk (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:117794)
>     at Vk (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:114849)
>     at og (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:49221)
>     at gl (file:///private/var/folders/gp/wsnqxfjs64g60x7gcdbtbwqr0000gn/T/AppTranslocation/BA9BC7E5-5A2A-429B-87BE-A92E2741810B/d/Flipper.app/Contents/Resources/app.asar/bundle.js:138:115155)

## To Reproduce

- Open Flipper -> Network -> Mock
- Click X to remove network call.
- Confirm and crash is shown
- Clear error and try again results in similar error

Reproduces every time regardless of mock network call set values.

## Environment

- M1 Mac
- Flipper version: repros on both 147.1 and 148.0
- Android Emulator: Pixel_3a_API_32

**Comment by commonsguy** [comment]
Also repros on 0.171.1 (macOS, Android 13 Pixel 5).

**Comment by kongxiaojun** [comment]
I fixed it. See https://github.com/facebook/flipper/pull/4403 .
