### ISSUE TITLE
Docs: can't build desktop app using instructions w/ latest node/yarn version

### ISSUE THREAD

**Issue by kenyee** [facebook/flipper#3988]
The root readme instructions just say go into the desktop folder and run "yarn" and "yarn start".
➜  desktop git:(main) yarn --version
1.19.2
➜  desktop git:(main) node --version
v18.7.0

My yarn/node versions are higher than the min required in the docs.
Yarn seems to download everything, but when doing a yarn start, I get this cryptic error that looks like it's coming from the metro module and the app stays forever at the "Loading..." msg on a blank background:

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/ad1b213c-1b60-4602-8a84-f7d535da6611
objc[16682]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x23ae4db50) and /Users/keny/workspace/flipper/desktop/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1094b13c8). One of the two will be used. Which one is undefined.
Loading React devtools from disk /Users/keny/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi
(node:16508) ExtensionLoadWarning: Warnings loading extension at /Users/keny/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

(Use `Electron --trace-warnings ...` to show where the warning was created)
 BUNDLE  app/src/init.tsx

error: Error: Unable to resolve module @ant-design/icons-svg/es/asn/AccountBookFilled from /Users/keny/workspace/flipper/desktop/node_modules/@ant-design/icons/es/icons/AccountBookFilled.js: @ant-design/icons-svg/es/asn/AccountBookFilled could not be found within the project or in these directories:
  node_modules
  3 | // DON NOT EDIT IT MANUALLY
  4 | import * as React from 'react';
> 5 | import AccountBookFilledSvg from "@ant-design/icons-svg/es/asn/AccountBookFilled";
    |                                   ^
  6 | import AntdIcon from '../components/AntdIcon';
  7 |
  8 | var AccountBookFilled = function AccountBookFilled(props, ref) {
    at ModuleResolver.resolveDependency (/Users/keny/workspace/flipper/desktop/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/Users/keny/workspace/flipper/desktop/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Users/keny/workspace/flipper/desktop/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/keny/workspace/flipper/desktop/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/keny/workspace/flipper/desktop/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/keny/workspace/flipper/desktop/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/keny/workspace/flipper/desktop/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at addDependency (/Users/keny/workspace/flipper/desktop/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 0)
```

**Comment by kenyee** [comment]
FYI, tried this on another laptop...same version of yarn/node and it "yarn start" works 🤯 

Also, would be nice to have a few pointers in the docs on breakpoints and general architecture of the desktop app so noobs don't have to figure all this out the hard way...
