### ISSUE TITLE
Flipper desktop (0.166.0) failing to load `flipper-plugin-react-devtools`

### ISSUE THREAD

**Issue by aajahid** [facebook/flipper#4203]
## 🐛 Bug Report
Flipper desktop (0.166.0) failing to load `flipper-plugin-react-devtools` 
Downgrading seems to fix the issue ( I downgraded to 0.164.0 and the react-devtool started working fine again )

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/1908862/195274106-6973b3b2-e26f-4f10-be79-c7e8e4555070.png">

```Failed to start a server add on flipper-plugin-react-devtools http://localhost:8081/ 
Error: Cannot find module 'C:Usersjahidlipper
esourcesapp.asar.unpackeddefaultPluginslipper-plugin-react-devtoolsdistserverAddOn.js'
Require stack:

- C:\Users\jahid\flipper\resources\app.asar\index.html

    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)

    at Function.i._resolveFilename (node:electron/js2c/renderer_init:33:1095)

    at Module._load (node:internal/modules/cjs/loader:785:27)

    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)

    at Function.i._load (node:electron/js2c/renderer_init:33:356)

    at Module.require (node:internal/modules/cjs/loader:1012:19)

    at Object.apply (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:15:760)

    at require (node:internal/modules/cjs/helpers:102:18)

    at eval (eval at loadServerAddOn (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:932:1424), <anonymous>:1:1)

    at loadServerAddOn (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:932:1424)

    at Function.start (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:928:768)

    at ServerAddOnManager.startServerAddOn (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:927:2418)

    at new ServerAddOnManager (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:927:557)

    at PluginManager.startServerAddOn (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:671:5700)

    at plugins-server-add-on-start (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:273:7774)

    at FlipperServerImpl.exec (file:///C:/Users/jahid/flipper/resources/app.asar/bundle.js:273:12866)
code: "MODULE_NOT_FOUND"
requireStack: Array(1)
0: "C:\Users\jahid\flipper\resources\app.asar\index.html"
```

## To Reproduce
Run a react-native app and see the logs.

## Environment
Windows 11 Pro, 21H2, 22000.1098
Flipper desktop (0.166.0)

**Comment by aigoncharov** [comment]
@aajahid thanks for your report! Do you still see it o the latest Flipper (0.170)?

**Comment by aajahid** [comment]
> @aajahid thanks for your report! Do you still see it o the latest Flipper (0.170)?

I did not test on latest flipper. I guess I have to build it from source? ( Flipper app tells me there is an update and it downloads `0.166.0`. I thought it was the latest version.)

I'll see if I can figure out how to build the from source and try that out.

Thanks.

**Comment by aigoncharov** [comment]
Ah, yeah. We have the release pipeline broken. It should be fixed on Monday. I'll ping you here once it is.

**Comment by aajahid** [comment]
@aigoncharov I did built from source and latest version ( 0.170.0 ) also have the same issue. 
Here is a screenshot of that. 

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1908862/196021303-02b1d759-7118-4765-97d4-7b7872c90b01.png">

**Comment by CodeWithShamim** [comment]
same issue

**Comment by ZMomo** [comment]
Same issue aswell in v0.171.1
