### ISSUE TITLE
yarn build fails with 404 asset

### ISSUE THREAD

**Issue by seanxiaoxiao** [facebook/flipper#5002]
## 🐛 Bug Report
Trying to do `yarn build --mac-dmg` and got one of the icon asset fail to load and that breaks the build

> /Users/sxiao3/Snapchat/Dev/flipper/desktop/node_modules/metro-hermes-compiler/src/emhermesc.js:77
>           throw ex;
>           ^
> 
> RuntimeError: abort(Error: Could not download the icon [object Object] from https://facebook.com/images/assets_DO_NOT_HARDCODE/facebook_icons/app-dailies_filled_12.png: got status 404). Build with -s ASSERTIONS=1 for more info.
>     at process.abort (/Users/sxiao3/Snapchat/Dev/flipper/desktop/node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
>     at process.emit (node:events:513:28)
>     at process.emit (node:domain:489:12)
>     at process.emit (/Users/sxiao3/Snapchat/Dev/flipper/desktop/node_modules/source-map-support/source-map-support.js:495:21)
>     at processEmit [as emit] (/Users/sxiao3/Snapchat/Dev/flipper/desktop/node_modules/signal-exit/index.js:161:32)
>     at emit (node:internal/process/promises:140:20)
>     at processPromiseRejections (node:internal/process/promises:274:27)
>     at processTicksAndRejections (node:internal/process/task_queues:97:32)
> error Command failed with exit code 7.

**Comment by seanxiaoxiao** [comment]
Are we trying to download with the url generated from here https://github.com/facebook/flipper/blob/main/desktop/scripts/build-icons.tsx#L99

**Comment by yhelwa** [comment]
Getting a similar error

> RuntimeError: abort(Error: Could not download the icon [object Object] from https://facebook.com/assets/?name=apps&variant=filled&size=16&set=facebook_icons&density=1x: got status 404). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/youssefhelwa_1/flipper/desktop/node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
    at process.emit (node:events:514:28)
    at process.emit (node:domain:489:12)
    at process.emit (/Users/youssefhelwa_1/flipper/desktop/node_modules/source-map-support/source-map-support.js:495:21)
    at processEmit [as emit] (/Users/youssefhelwa_1/flipper/desktop/node_modules/signal-exit/index.js:161:32)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
