### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by waqasmunir05** [facebook/flipper#5046]
## 🐛 Bug Report
TypeError: Cannot use 'in' operator to search for 'cmd' in undefined

Flipper version: 0.211.0

Component stack:

    at DataTable (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4223:2083)
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at Right (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1598:2933)
    at ConnectivityLogs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4879:4891)
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at div
    at TabPane (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3572:1397)
    at Tab (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4250:2563)
    at div
    at div
    at TabPanelList (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3571:1398)
    at div
    at Tabs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3559:2598)
    at Tabs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3557:2056)
    at Tabs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4250:1538)
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at TroubleshootingHub
    at div
    at div
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3697:1182
    at div
    at DomWrapper (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3301:1599)
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3291:2026
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3696:1656
    at div
    at div
    at Dialog (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3693:1697)
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3334:369
    at PortalWrapper (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3648:2471)
    at DialogWrap (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3692:1459)
    at Modal (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3736:2355)
    at TroubleshootingModal (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4557:13790)
    at TroubleshootMenu (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4557:11063)
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at Navbar
    at TrackingScope (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1581:2065)
    at WithTrackingScope
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at Top (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1598:2699)
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at Bottom (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1598:2779)
    at div
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
    at SandyApp (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1573:1893)
    at TooltipProvider (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4310:2814)
    at PersistGate (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4903:3375)
    at Provider (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1509:1379)
    at AppFrame (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1458:1841)

Error stacktrace:
TypeError: Cannot use 'in' operator to search for 'cmd' in undefined
    at isShellCommand (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4879:3051)
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4879:5140
    at triggerSelection (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4223:9796)
    at ik (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1558:101881)
    at Yk (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1558:120940)
    at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1558:118932
    at J (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1570:1587)
    at Immediate.R [as _onImmediate] (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1570:1972)
    at processImmediate (node:internal/timers:464:21)

**Comment by vanlethi99** [comment]
I also faced this issue, any solution for this?

**Comment by vanlethi99** [comment]
> ## 🐛 Bug Report
> TypeError: Cannot use 'in' operator to search for 'cmd' in undefined
> 
> Flipper version: 0.211.0
> 
> Component stack:
> 
> ```
> at DataTable (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4223:2083)
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at Right (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1598:2933)
> at ConnectivityLogs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4879:4891)
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at div
> at TabPane (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3572:1397)
> at Tab (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4250:2563)
> at div
> at div
> at TabPanelList (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3571:1398)
> at div
> at Tabs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3559:2598)
> at Tabs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3557:2056)
> at Tabs (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4250:1538)
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at TroubleshootingHub
> at div
> at div
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3697:1182
> at div
> at DomWrapper (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3301:1599)
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3291:2026
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3696:1656
> at div
> at div
> at Dialog (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3693:1697)
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3334:369
> at PortalWrapper (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3648:2471)
> at DialogWrap (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3692:1459)
> at Modal (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:3736:2355)
> at TroubleshootingModal (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4557:13790)
> at TroubleshootMenu (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4557:11063)
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at Navbar
> at TrackingScope (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1581:2065)
> at WithTrackingScope
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at Top (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1598:2699)
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at Bottom (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1598:2779)
> at div
> at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1481:2107
> at SandyApp (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1573:1893)
> at TooltipProvider (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4310:2814)
> at PersistGate (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4903:3375)
> at Provider (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1509:1379)
> at AppFrame (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1458:1841)
> ```
> 
> Error stacktrace: TypeError: Cannot use 'in' operator to search for 'cmd' in undefined at isShellCommand (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4879:3051) at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4879:5140 at triggerSelection (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:4223:9796) at ik (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1558:101881) at Yk (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1558:120940) at file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1558:118932 at J (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1570:1587) at Immediate.R [as _onImmediate] (file:///C:/Users/waqas.munir/Downloads/Flipper-win/resources/app.asar/bundle.js:1570:1972) at processImmediate (node:internal/timers:464:21)

This issue maybe was caused because the wrong located of idb and idb-companion in, you can follow this [https://stackoverflow.com/questions/72696726/flipper-desktop-failed-to-provide-certificates-error-from-flipper-desktop](url)
