### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'cmd' in undefined

### ISSUE THREAD

**Issue by vanlethi99** [facebook/flipper#5050]
I have faced this issue during connecting Flipper with iPhone real device, does anyone have a solution for this?

## 🐛 Bug Report
TypeError: Cannot use 'in' operator to search for 'cmd' in undefined

Flipper version: 0.210.1

Component stack:

    at DataTable (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4223:2083)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at Right (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1598:2933)
    at ConnectivityLogs (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4879:4891)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at div
    at TabPane (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3572:1397)
    at Tab (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4250:2563)
    at div
    at div
    at TabPanelList (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3571:1398)
    at div
    at Tabs (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3559:2598)
    at Tabs (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3557:2056)
    at Tabs (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4250:1538)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at TroubleshootingHub
    at div
    at div
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3697:1182
    at div
    at DomWrapper (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3301:1599)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3291:2026
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3696:1656
    at div
    at div
    at Dialog (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3693:1697)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3334:369
    at PortalWrapper (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3648:2471)
    at DialogWrap (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3692:1459)
    at Modal (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:3736:2355)
    at TroubleshootingModal (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4557:13790)
    at TroubleshootMenu (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4557:11063)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at Navbar
    at TrackingScope (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1581:2065)
    at WithTrackingScope
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at Top (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1598:2699)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at Bottom (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1598:2779)
    at div
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1481:2107
    at SandyApp (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1573:1893)
    at TooltipProvider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4310:2814)
    at PersistGate (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4903:3375)
    at Provider (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1509:1379)
    at AppFrame (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1458:1841)

Error stacktrace:
TypeError: Cannot use 'in' operator to search for 'cmd' in undefined
    at isShellCommand (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4879:3051)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4879:5140
    at triggerSelection (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:4223:9796)
    at ik (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1558:101881)
    at Yk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1558:120940)
    at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1558:118932
    at J (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1570:1587)
    at Immediate.R [as _onImmediate] (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1570:1972)
    at processImmediate (node:internal/timers:464:21)

**Comment by vanlethi99** [comment]
This issue was caused because the wrong located of idb and idb-companion in, I follow this and the issue has been 
fixed. [https://stackoverflow.com/questions/72696726/flipper-desktop-failed-to-provide-certificates-error-from-flipper-desktop](url)
<img width="569" alt="Screenshot 2023-08-17 at 10 31 21" src="https://github.com/facebook/flipper/assets/81425335/3425a4af-1228-4509-9a16-8d7b5acf002c">
