### ISSUE TITLE
Unsupported class file major version 61 with Flipper 0.221.0

### ISSUE THREAD

**Issue by ZacSweers** [facebook/flipper#5168]
## 🐛 Bug Report

It appears the latest flipper release is build targeting java 17, which cannot run on android devices. R8 reports this fairly clearly

```
Error in /var/lib/buildkite-agent/builds/mbr-buildkite-agent-android-iad-isvdob-1/slack/android-pull-request/app/build/intermediates/keeper/internalReleaseAndroidTest/classes.jar:com/facebook/flipper/plugins/uidebugger/UIDebuggerFlipperPlugin.class:
--
  | java.lang.IllegalArgumentException: Unsupported class file major version 61
  | Compilation failed with an internal error.
  | com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /var/lib/buildkite-agent/builds/mbr-buildkite-agent-android-iad-isvdob-1/slack/android-pull-request/app/build/intermediates/keeper/internalReleaseAndroidTest/classes.jar:com/facebook/flipper/plugins/uidebugger/UIDebuggerFlipperPlugin.class
  | at Version.fakeStackEntry(Version_3.0.9-dev.java:0)
  | at com.android.tools.r8.utils.ExceptionUtils.failWithFakeEntry(ExceptionUtils.java:130)
  | at com.android.tools.r8.utils.ExceptionUtils.failCompilation(ExceptionUtils.java:80)
  | at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:74)
  | at com.android.tools.r8.tracereferences.TraceReferences.run(TraceReferences.java:30)
  | at com.android.tools.r8.tracereferences.TraceReferences.run(TraceReferences.java:84)
  | at com.android.tools.r8.tracereferences.TraceReferences.lambda$main$2(TraceReferences.java:98)
  | at com.android.tools.r8.utils.ExceptionUtils.withMainProgramHandler(ExceptionUtils.java:177)
  | at com.android.tools.r8.tracereferences.TraceReferences.main(TraceReferences.java:98)
  | Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
  | at com.android.tools.r8.org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
  | at com.android.tools.r8.org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
  | at com.android.tools.r8.org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
  | at com.android.tools.r8.graph.JarClassFileReader.internalRead(JarClassFileReader.java:107)
  | at com.android.tools.r8.graph.JarClassFileReader.lambda$read$0(JarClassFileReader.java:94)
  | at com.android.tools.r8.utils.ExceptionUtils.lambda$withOriginAndPositionAttachmentHandler$1(ExceptionUtils.java:233)
  | at com.android.tools.r8.utils.ExceptionUtils.withOriginAndPositionAttachmentHandler(ExceptionUtils.java:241)
  | at com.android.tools.r8.utils.ExceptionUtils.withOriginAndPositionAttachmentHandler(ExceptionUtils.java:229)
  | at com.android.tools.r8.utils.ExceptionUtils.withOriginAttachmentHandler(ExceptionUtils.java:220)
  | at com.android.tools.r8.graph.JarClassFileReader.read(JarClassFileReader.java:93)
  | at com.android.tools.r8.graph.JarClassFileReader.read(JarClassFileReader.java:89)
  | at com.android.tools.r8.dex.ApplicationReader$ClassReader.lambda$readClassSources$1(ApplicationReader.java:338)


```

## To Reproduce

Try to use flipper 0.221.0 on any android builds

**Comment by G00fY2** [comment]
We don't see any compile errors and flipper is working fine, also when using R8. But we also use JvmTarget 17 in our Android project (which should be supported by AGP 8.x/R8).

**Comment by ZacSweers** [comment]
R8 only supports backporting records and it was only introduced in Flamingo, so it's fairly fresh :)

We can update but def think 11 would be better for now
