### ISSUE TITLE
Smasung No1_S6: No route to flipper found. 

### ISSUE THREAD

**Issue by caiiiycuk** [facebook/flipper#524]
## 🐛 Bug Report
I am using flipper version 0.23.4, desktop from repository HEAD. I successfully integrated flipper in my app. And everything works in emulator device. But it not working on real device Samsung NO1_S6.
![IMG_20190823_161620](https://user-images.githubusercontent.com/1727152/63581644-be164000-c5c1-11e9-80bf-31ebd7684f35.jpg)

There is no errors on flipper desktop side:
![1](https://user-images.githubusercontent.com/1727152/63581857-206f4080-c5c2-11e9-8d4e-c022ed332b7e.jpg)

I checked this (https://github.com/facebook/flipper/issues/92), in my case command `adb shell
run-as <package>` work fine.

I also tried to change default ports, but no luck.

## Environment
Android: 4.2.1 (rooted)
Desktop: Ubuntu 19.03
Flipper latest.

**Comment by caiiiycuk** [comment]
Exception on flipper desktop screen:
```
"FailError: Failure: 'closed'
    at file:///home/caiiiycuk/ide/flipper/dist/linux-unpacked/resources/app/bundle.js:64674:31
    at tryCatcher (file:///home/caiiiycuk/ide/flipper/dist/linux-unpacked/resources/app/bundle.js:63670:27)
    at Promise._settlePromiseFromHandler (file:///home/caiiiycuk/ide/flipper/dist/linux-unpacked/resources/app/bundle.js:61665:37)
    at Promise._settlePromiseAt (file:///home/caiiiycuk/ide/flipper/dist/linux-unpacked/resources/app/bundle.js:61748:22)
    at Async._drainQueue (file:///home/caiiiycuk/ide/flipper/dist/linux-unpacked/resources/app/bundle.js:59043:16)
    at Async._drainQueues (file:///home/caiiiycuk/ide/flipper/dist/linux-unpacked/resources/app/bundle.js:59048:16)
    at MutationObserver.Async.drainQueues (file:///home/caiiiycuk/ide/flipper/dist/linux-unpacked/resources/app/bundle.js:58915:18)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)"
```

**Comment by spatenotte** [comment]
Commenting here, since I'm having the same issue on a Nexus 6P, running Android 8.1.0.
I am using Flipper 0.27.0, both on the client app and SDK library.

![image](https://user-images.githubusercontent.com/5433694/68169650-d4c20700-ff21-11e9-8499-67659dadda18.png)
