### ISSUE TITLE
Question: Flipper is not detecting apps after upgrading to RNv0.72

### ISSUE THREAD

**Issue by dusanristic** [facebook/flipper#5261]
After I upgraded my RN project to v0.72, Flipper stopped detecting my apps. Besides not showing the app, it is displaying an 'DEVICE DISCONNECTED' error label.
Beside that, React DevTools work properly, but the plugins do not, as if I didn't properly initialize them. 
To troubleshoot, I created a barebone project, and in that scenario, Flipper works as expected. This indicates that something went wrong during the upgrade process, but I'm having trouble pinpointing the exact cause.

I'd appreciate any insights or suggestions you might have to resolve this issue. 

Here are some relevant libraries and versions I'm using:
- react-native: 0.72.6
- react-native-flipper: 0.200.0
- Flipper app: 0.200.0

Additionally, I've encountered an error in Flipper Logs, and while I'm not sure if it's related, I'll provide the error details for reference:
> "onerror" event intercepted: Uncaught Error: Cannot add node "1" because a node with that id is already in the Store. 
> {source: "/Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/bundle.js", lineno: 11, colno: 31168, error: Error, stack: "Error: Cannot add node "1" because a node with that id is already in the Store.
>     at /Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/bundle.js:7694:19083
>     at w.emit (/Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/bundle.js:11:31118)
>     at /Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/bundle.js:11:29130
>     at /Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/bundle.js:7795:203209
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:946:399
>     at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1557:115115)
>     at file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:946:380
>     at EventEmitter.subscriptionCb (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1210:548)
>     at EventEmitter.emit (node:events:390:28)
>     at FlipperServerImpl.emit (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:10:13828)
>     at ServerAddOnModuleToDesktopConnection.onMessage (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:936:939)
>     at ServerAddOnModuleToDesktopConnection.emit (node:events:390:28)
>     at ServerAddOnModuleToDesktopConnection.send (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:937:1263)
>     at ne.<anonymous> (/Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/serverAddOn.js:321:18051)
>     at ne.emit (node:events:390:28)
>     at uo.Yv (/Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/serverAddOn.js:1:36577)"}
> source: "/Applications/Flipper.app/Contents/Resources/app.asar.unpacked/defaultPlugins/flipper-plugin-react-devtools/dist/bundle.js"

Please let me know if you need any additional info.

**Comment by rajeshp2511** [comment]
same issue

**Comment by erez-unitronics** [comment]
same

**Comment by Hos1g4k1** [comment]
Same issue

**Comment by simonadenic** [comment]
Same issue.

**Comment by nickprihodko** [comment]
+ 1

**Comment by NjegosPetrovic** [comment]
Same.

**Comment by dusanristic** [comment]
Additionally note, everything works well on Android, so this is an iOS-specific problem.

**Comment by rajeshp2511** [comment]
i am facing on android as well

**Comment by dusanristic** [comment]
Hey guys, related to iOS, [this issue](https://github.com/facebook/flipper/issues/4657) helped me. Make sure to call 
```
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif
```
inside _- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions_ function, before return statement.

@rajeshp2511 Are devices are shown at all on Flipper, or you only have problem with showing app inside it?

**Comment by dusanristic** [comment]
Additionally, make sure to 
- use Flipper. 0.163.0, as newer versions has a problem compiling
- set arm64 to be excluded architecture for all builds (check the image below)
![Screenshot 2023-11-07 at 11 23 57](https://github.com/facebook/flipper/assets/38317456/4770561b-e219-42c8-b53f-8300765315a9)

**Comment by gyanbhartip** [comment]
> Additionally note, everything works well on Android, so this is an iOS-specific problem.

With everything setup as the official guide, does not work on Android. Getting "Metro is connected but no Hermes apps were found" and similar errors in the Flipper logs as OP.

**Comment by rajeshp2511** [comment]
@dusanristic Device is showing there but app is not visible

![image](https://github.com/facebook/flipper/assets/58897775/cce74145-030f-4bd5-8dac-f87e0d985a03)

**Comment by marcshilling** [comment]
> Hey guys, related to iOS, [this issue](https://github.com/facebook/flipper/issues/4657) helped me. Make sure to call
> 
> ```
> #ifdef FB_SONARKIT_ENABLED
>   InitializeFlipper(application);
> #endif
> ```
> 
> inside _- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions_ function, before **return** statement.
> 
> @rajeshp2511 Do devices show up at all in Flipper, or do you only have a problem with displaying the app inside it?

This is the answer. The newer versions of RN remove RCTAppSetupUtils so the [React Native 0.68+ install instructions](https://fbflipper.com/docs/getting-started/react-native-ios/#react-native-068) no longer apply. But use the [React Native 0.67 instructions](https://fbflipper.com/docs/getting-started/react-native-ios/#react-native-067) again and it will work. Docs should be updated!

**Comment by amorimcode** [comment]
@rajeshp2511 same problem here, only on android
