### ISSUE TITLE
Building standalone on linux fails

### ISSUE THREAD

**Issue by eygraber** [facebook/flipper#527]
I'm on Ubuntu 18.04.3 and if I try running `yarn build --linux --version 0.23.4` I get the following error:

```
yarn run v1.17.3
$ yarn rm-dist && cross-env NODE_ENV=production node scripts/build-release.js $@ --linux --version 0.23.4
$ rm -rf dist
/home/eli/workspace/flipper/scripts/build-utils.js:36
          defaultPlugins.map(({entry, rootDir, out, ...plugin}) => ({
                                                    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/eli/workspace/flipper/scripts/build-release.js:19:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by passy** [comment]
@eygraber Pardon the late response. You're likely stuck on an old version of node. I'm not exactly sure what the minimum version is we require, but ideally you'd build with the most recent stable. We can't provide backwards compatibility.
