### ISSUE TITLE
Question: Cannot start Flipper via yarn start in 0.238.0

### ISSUE THREAD

**Issue by ChillingVan** [facebook/flipper#5293]
Version: 0.238.0
Environment: mac OS Monterey. Apple M1 Pro
Issue log：
```
UI Debugger - /Users/ziling.fan/Documents/work/opensource/flipper/desktop/plugins/public/ui-debugger.
[flipper-server][bootstrap] Companion environment initialised (17.309500000439584 ms)
Checking for certificates validity
Checking certificate was issued by current CA
Checking certs can be used for TLS
Not all certificates are valid, generating new ones Error: error:0A00018E:SSL routines::ca md too weak
    at node:internal/tls/secure-context:70:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:68:3)
    at configSecureContext (node:internal/tls/secure-context:161:5)
    at createSecureContext (node:_tls_common:116:3)
    at /Users/ziling.fan/Documents/work/opensource/flipper/desktop/flipper-server-core/lib/app-connectivity/certificate-exchange/certificate-utils.js:173:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  library: 'SSL routines',
  reason: 'ca md too weak',
  code: 'ERR_SSL_CA_MD_TOO_WEAK'
}
Creating new server certificate
Generate client authentication token
Checking for certificates validity
Checking certificate was issued by current CA
Checking certs can be used for TLS
Not all certificates are valid, generating new ones Error: error:0A00018E:SSL routines::ca md too weak
    at node:internal/tls/secure-context:70:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:68:3)
    at configSecureContext (node:internal/tls/secure-context:161:5)
    at createSecureContext (node:_tls_common:116:3)
    at /Users/ziling.fan/Documents/work/opensource/flipper/desktop/flipper-server-core/lib/app-connectivity/certificate-exchange/certificate-utils.js:173:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  library: 'SSL routines',
  reason: 'ca md too weak',
  code: 'ERR_SSL_CA_MD_TOO_WEAK'
}
Creating new server certificate
Verify authentication token
Either token has expired or is invalid
Generate client authentication token
Checking for certificates validity
[ws] secure server listening at port:  8088
Checking certificate was issued by current CA
Checking certs can be used for TLS
Not all certificates are valid, generating new ones Error: error:0A00018E:SSL routines::ca md too weak
    at node:internal/tls/secure-context:70:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:68:3)
    at configSecureContext (node:internal/tls/secure-context:161:5)
    at createSecureContext (node:_tls_common:116:3)
    at /Users/ziling.fan/Documents/work/opensource/flipper/desktop/flipper-server-core/lib/app-connectivity/certificate-exchange/certificate-utils.js:173:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  library: 'SSL routines',
  reason: 'ca md too weak',
  code: 'ERR_SSL_CA_MD_TOO_WEAK'
}
Creating new server certificate
```
And then it just stops running and the browser just shows "Loading" without any more progress.

Command used:
```
git clone https://github.com/facebook/flipper.git
cd flipper/desktop
yarn
yarn start
```

**Comment by ChillingVan** [comment]
Tried both 0.217.0 and 0.218.0, but they show issue same like this: https://github.com/facebook/flipper/issues/5142

**Comment by ChillingVan** [comment]
openssl version: OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)

**Comment by ChillingVan** [comment]
But It works fine with
```
yarn start-electron
```
