### ISSUE TITLE
No matching version found for flipper-common@0.251.0

### ISSUE THREAD

**Issue by ilyeshadji** [facebook/flipper#5555]
## 🐛 Bug Report
When trying to setup and open Flipper on my Mac, the app does not open. It jumps for a while, but never works.

Here are the logs:

```bash

2033 verbose stack flipper-common: No matching version found for flipper-common@0.251.0.
2033 verbose stack     at module.exports (/Users/ilyeshadji/.nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
2033 verbose stack     at RegistryFetcher.manifest (/Users/ilyeshadji/.nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:130:22)
2034 verbose cwd /Users/ilyeshadji
2035 verbose Darwin 23.4.0
2036 verbose node v20.11.1
2037 verbose npm  v10.5.0
2038 error code ETARGET
2039 error notarget No matching version found for flipper-common@0.251.0.
2040 error notarget In most cases you or one of your dependencies are requesting
2040 error notarget a package version that doesn't exist.
2041 verbose exit 1

```

## To Reproduce
Download flipper using `brew install --cask flipper` as per the documentation https://fbflipper.com/docs/getting-started/

Run `npx flipper-server`

## Environment
OS: MacOs
Chip: Apple M3 Pro
Version: Sonoma 14.4.1

**Comment by anupatgithub** [comment]
Same issue, was not able to start the Flipper Server app so tried this as suggested but getting the same issue as posted here.

**Comment by easyecom-manu** [comment]
same issues

**Comment by Prai5e** [comment]
Please i tried running `npm install`, for which i encountered **same error**.  On my windows 11 PC

**Comment by muffin9** [comment]
Why don't you download and run this version of flipper?
https://flipper.en.uptodown.com/mac/download

**Comment by sxhieen** [comment]
same issue on my Windows 10 PC
