### ISSUE TITLE
flipper can't detect idb-companion 

### ISSUE THREAD

**Issue by lmb-it** [facebook/flipper#5661]
![Screenshot 2024-07-27 at 2 44 00 PM](https://github.com/user-attachments/assets/b6374d6e-8031-4173-b650-422c6a38de27)

Only one step got failed and here is the error

`Command "/Library/Frameworks/Python.framework/Versions/3.12/bin/idb list-targets --json" failed to execute with output: Command failed: /Library/Frameworks/Python.framework/Versions/3.12/bin/idb list-targets --json
2024-07-27 14:43:33,721 [ERROR] - root - Exception thrown in main
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/cli/main.py", line 313, in gen_main
    await root_command.run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/command.py", line 90, in run
    return await self.resolve_command_from_args(args).run(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/cli/__init__.py", line 106, in run
    await self._run_impl(args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/cli/__init__.py", line 149, in _run_impl
    await self.run_with_manager(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/cli/commands/target.py", line 188, in run_with_manager
    targets = await manager.list_targets(only=only)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/logging.py", line 113, in _async_wrapper
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/logging.py", line 88, in _async_wrapper
    value = await function(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/grpc/management.py", line 197, in list_targets
    (local_targets, connected_targets) = await asyncio.gather(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/grpc/management.py", line 195, in _list_local_targets
    return await companion.list_targets(only=only)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/logging.py", line 113, in _async_wrapper
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/logging.py", line 88, in _async_wrapper
    value = await function(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/companion.py", line 383, in list_targets
    output = await self._run_companion_command(arguments=arguments, timeout=timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/companion.py", line 161, in _run_companion_command
    async with self._start_companion_command(arguments=arguments) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/idb/common/companion.py", line 137, in _start_companion_command
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1744, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/unix_events.py", line 211, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/unix_events.py", line 820, in _start
    self._proc = subprocess.Popen(
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/idb_companion'`

the last line is FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/idb_companion
here is the file located
![Screenshot 2024-07-27 at 2 46 00 PM](https://github.com/user-attachments/assets/910d920f-af5a-4741-ae70-31f0c2834f86)

what could be the issue?

Thank you
I

**Comment by ablof** [comment]
It's in `homebrew`, this solved it for me: `sudo ln -s /opt/homebrew/bin/idb_companion /usr/local/bin/idb_companion`

**Comment by h2oearth** [comment]
Thank you @ablof  life saver!
