### ISSUE TITLE
Command "yarn install" failing due to illegal characters

### ISSUE THREAD

**Issue by bizzguy** [facebook/flipper#573]
## 🐛 Bug Report
When attempting to create a custom version of Flipper, the "yarn install" command is failing.

## To Reproduce
1. Download current version (commit #d310027d888677616238514ebf983655b2ad21f3 )
2. Remove directory "node_modules"
3. Run "yarn install"

## Expected Behavior
All packages should be successfully installed.

## Actual Behavior

yarn install v1.17.3
$ yarn config set ignore-engines
yarn config v1.17.3
success Set "ignore-engines" to true.
✨  Done in 0.05s.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-fbjs@3.1.0" has incorrect peer dependency "eslint@^5.1.0".
warning " > eslint-config-fbjs@3.1.0" has incorrect peer dependency "eslint-plugin-flowtype@^2.43.0".
[4/4] 🔨  Building fresh packages...
$ node scripts/yarn-install.js
Installing dependencies for 19 plugins
warning Resolution field "temp@0.9.0" is incompatible with requested version "temp@0.8.3"

❌  Installing plugin dependencies failed.
Error: Command failed: yarn --mutex network:30330
error package.json: Name contains illegal characters

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn --mutex network:30330',
  stdout: 'yarn install v1.17.3\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr: 'error package.json: Name contains illegal characters\n'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by bizzguy** [comment]
Problem with custom plugin, not "master" repo.
