### ISSUE TITLE
can't running on windows

### ISSUE THREAD

**Issue by bytecho** [facebook/flipper#62]
i cloned this repo to my computer.and run command:
```
cd Sonar
yarn
```
yarn runned a while,then aborted.this is some info in yarn-err.log:

```
Arguments: 
  D:\Nodejs\node.exe D:\Yarn\bin\yarn.js


Yarn version: 
  1.5.1

Node version: 
  8.11.1

Platform: 
  win32 x64

Trace: 
  Error: Command failed.
  Exit code: 1
  Command: C:\WINDOWS\system32\cmd.exe
  Arguments: /d /s /c node node_modules/electron/install.js && node scripts/yarn-install.js
  Directory: F:\github\Sonar
  Output:
  
      at ProcessTermError.MessageError (D:\Yarn\lib\cli.js:186:110)
      at new ProcessTermError (D:\Yarn\lib\cli.js:226:113)
      at ChildProcess.<anonymous> (D:\Yarn\lib\cli.js:30281:17)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by passy** [comment]
That looks like it might be the electron part of the building failing? Does running `node node_modules/electron/install.js` cause any errors on its own?

**Comment by Aexyn** [comment]
I am getting this error

>  PS C:\Aman\sonar\Sonar> yarn
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-fbjs@2.0.1" has incorrect peer dependency "babel-eslint@^7.2.3".
[4/4] Building fresh packages...
$ node node_modules/electron/install.js && node scripts/yarn-install.js
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: spawn yarn ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by bytecho** [comment]
i update sonar and run it again,but there is another error,still on windows:
$ yarn
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from instal
lation.
error 7zip-bin-mac@1.0.1: The platform "win32" is incompatible with this module.
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by danielbuechele** [comment]
this should be fixed in the latest commit

**Comment by bytecho** [comment]
@danielbuechele  i update sonar ,and i get the first error again.

```
$ yarn
yarn install v1.7.0
[1/4] Resolving packages...
success Already up-to-date.
$ node node_modules/electron/install.js && node scripts/yarn-install.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by yljjiava** [comment]
me too, same problem

**Comment by yljjiava** [comment]
问题已经解决，需要修改 F:\Sonar\scripts\yarn-install.js和D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js两个文件，修改地方如下：
1.index.js在271行添加conf.shell=true
2.yarn-install.js 在39行修改成 const yarn = spawn(YARN_PATH, ['--mutex', 'file'], {
              cwd,
			  shell:true
            });
3.删除sonar目录下node_modules目录,重新运行npm install 安装

**Comment by xiphirx** [comment]
Closing since apparently it's been fixed
