### ISSUE TITLE
WrongAbiError - Fatal Exception on launch of x86_64 Android Emulator with Flipper integration

### ISSUE THREAD

**Issue by DanEdgarTarget** [facebook/flipper#657]
## 🐛 Bug Report

I am unable to launch my built app w/ Flipper support in an Android x86 based emulator.

I can run on any ARM device, with no issues, just Android x86 / x86_64 emulators fail.

I appear to have all the needed pieces within my Gradle file regarding ABI support:
```
ndk {
      abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
    }
```

Output log from console on emulator launch:
```
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.target.ui.debug/lib-main/libfbjni.so" has unexpected e_machine: 40 (EM_ARM)
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1633)
        at com.facebook.soloader.SoLoader$1.load(SoLoader.java:393)
        at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
        at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:24)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:31)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
E/SoLoader: couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/com.target.ui.debug/lib-main/libfbjni.so" has unexpected e_machine: 40 (EM_ARM)
E/AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread
    Process: com.target.ui.debug, PID: 3250
    com.facebook.soloader.SoLoader$WrongAbiError: APK was built for a different platform
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:645)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:24)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:31)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
     Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/com.target.ui.debug/lib-main/libfbjni.so" has unexpected e_machine: 40 (EM_ARM)
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577) 
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525) 
        at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:24) 
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43) 
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:31) 
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25) 
E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.target.ui.debug, PID: 3250
    java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

## To Reproduce

Unknown, seems to only occur on some workstations for our Android app team.

## Environment

Android Studio 3.5.2

**Comment by krunk4ever** [comment]
I'm also hitting this error.

**Comment by krunk4ever** [comment]
Here's my stack traces:

```
    12:59:56.940    LoadedApk   Unable to instantiate appComponentFactory
java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.android.development-bmN51ZxbaZE4tYq7Rtk8Aw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.development-bmN51ZxbaZE4tYq7Rtk8Aw==/lib/x86, /data/app/com.example.android.development-bmN51ZxbaZE4tYq7Rtk8Aw==/base.apk!/lib/x86, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
    at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)
    at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
    at android.app.LoadedApk.getResources(LoadedApk.java:1032)
    at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
    at android.app.ActivityThread.access$1100(ActivityThread.java:199)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

    13:00:01.043    SoLoader    couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/com.example.android.development/lib-main/libfbjni.so" has unexpected e_machine: 40 (EM_ARM)

    13:00:01.044    AndroidRuntime  FATAL EXCEPTION: FlipperConnectionThread
Process: com.example.android.development, PID: 8128
com.facebook.soloader.SoLoader$WrongAbiError: APK was built for a different platform
    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:645)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
    at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:24)
    at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
    at com.facebook.jni.HybridData.<clinit>(HybridData.java:31)
    at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/com.example.android.development/lib-main/libfbjni.so" has unexpected e_machine: 40 (EM_ARM)
    at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
    ... 6 more

    13:00:01.044    AndroidRuntime  FATAL EXCEPTION: FlipperEventBaseThread
Process: com.example.android.development, PID: 8128
java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
    at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

**Comment by krunk4ever** [comment]
Note: We were using version 0.28.0

**Comment by passy** [comment]
I've just tried to repro this with our in-repo sample app on an x86_64 emu but without success. If you have any repro steps or ideally a repro repo, that'd be great.

**Comment by DanEdgarTarget** [comment]
I am going to apologize in advance for not being able to provide a repro repo.

On a 20+ person team, this issue is occurring on 2 workstations.

That leads me to believe that it isn't necessarily a repo based issue, but something environmental on the given machines?

I have tried things like repairing NDK, deleting all Gradle deps and forcing new, ... all to no avail.

Is there some core part of the `SoLoader` and/or AS / Gradle integration steps which could go bad? Is there some other Gradle / AS config issue which could lead to this independent of repo / source files? Is there some core permission issue with folders? .. Looking for any `SoLoader` help on this one.

**Comment by krunk4ever** [comment]
We were able to get some more data on this. It looks like it may be dependent on which Android API level your emulator is using. We got word that for some users, switching emulators help resolve the issue and so far my own testing has shown:

* Pixel 2 + API 28 = crash
* Pixel 2 + API 29 = launches
* Pixel + API 28 = crash

**Comment by saulmm** [comment]
<img width="1177" alt="Screenshot 2019-12-12 at 11 15 19" src="https://user-images.githubusercontent.com/3531999/70703896-48012a80-1cd1-11ea-8cee-b321a8f317bc.png">


```
Fatal exception

java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/com.mypopsy.android.staging/lib-main/libfbjni.so" is for EM_ARM (40) instead of EM_386 (3)

     FATAL EXCEPTION: FlipperConnectionThread
Process: {package-name}, PID: 10260
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/{package-name}/lib-main/libfbjni.so" is for EM_ARM (40) instead of EM_386 (3)
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
	at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:24)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
	at com.facebook.jni.HybridData.<clinit>(HybridData.java:31)
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
FATAL EXCEPTION: FlipperEventBaseThread
Process: {package-name}, PID: 10260
java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

**Comment by saulmm** [comment]
Having same issue on Pixel2, API29 as well

<img width="1177" alt="Screenshot 2019-12-12 at 11 15 19" src="https://user-images.githubusercontent.com/3531999/70703896-48012a80-1cd1-11ea-8cee-b321a8f317bc.png">


```
Fatal exception

java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/{package-name}/lib-main/libfbjni.so" is for EM_ARM (40) instead of EM_386 (3)

     FATAL EXCEPTION: FlipperConnectionThread
Process: {package-name}, PID: 10260
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: dlopen failed: "/data/data/{package-name}/lib-main/libfbjni.so" is for EM_ARM (40) instead of EM_386 (3)
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
	at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:24)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:43)
	at com.facebook.jni.HybridData.<clinit>(HybridData.java:31)
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
FATAL EXCEPTION: FlipperEventBaseThread
Process: {package-name}, PID: 10260
java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
	at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

**Comment by mfazekas** [comment]
I'm not sure if related but, we're seeming similiar issue with our Mapbox. https://github.com/react-native-mapbox-gl/maps/issues/737.

In our case from what i could understand the apk file was built sucesfully. If i looked into the apk file lib/x86/*.so was indeed for 386 architecture.

In our case on the first launch after install, the soloader extracted the `arm` libs to `lib-main`.
I've submitted an issue to https://github.com/facebook/SoLoader/issues/59

Also note that to reproduce i had to first unistall a working app.
