### ISSUE TITLE
UnsatisfiedLinkError (libevent_extra-2.1.so) with Flipper 0.32.2

### ISSUE THREAD

**Issue by EricAtPlanGrid** [facebook/flipper#754]
## 🐛 Bug Report

With nothing changed but an upgrade of the Flipper dependency version from 0.26.0 to 0.32.2, my app now crashes on launch, with this in logcat:

```
    --------- beginning of crash
2020-01-21 11:38:33.703 20293-20381/xxx.yyy.zzz E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.plangrid.android.devgrid, PID: 20293
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libflipper.so caused by: dlopen failed: library "libevent_extra-2.1.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.facebook.flipper.android.EventBase.<clinit>(EventBase.java:19)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
2020-01-21 11:38:33.703 20293-20382/xxx.yyy.zzz E/AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread
    Process: xxx.yyy.zzz, PID: 20293
    java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

## To Reproduce
Attempt to run a debug version of your app w/ Flipper enabled. Note: I have not yet tested the Flipper sample app, since I can't seem to get Android Studio to actually build it.

## Expected Behavior
The app does not crash on launch :)

## Environment
Android 9 on Samsung Galaxy Tab S6. Host OS: macOS Catalina. Android Studio 4.0

**Comment by EricAtPlanGrid** [comment]
Urgh this may have been a build issue. Investigating…

**Comment by EricAtPlanGrid** [comment]
(closing until I can get a handle on this better)

**Comment by tatsuyafujisaki** [comment]
I have the same issue. Did you find any solution?
